#ifndef MLPERF_LOADGEN_VERSION_H
#define MLPERF_LOADGEN_VERSION_H

// This header declares the versioning-related strings that will be defined in
// the version.cc file generated by version.py.

#include <string>

namespace mlperf {

const std::string& LoadgenVersion();
const std::string& LoadgenGitRevision();
const std::string& LoadgenBuildDateLocal();
const std::string& LoadgenBuildDateUtc();
const std::string& LoadgenGitCommitDate();
const std::string& LoadgenGitStatus();
const std::string& LoadgenGitLog();

}  // namespace mlperf

#endif  // MLPERF_LOADGEN_VERSION_H
