graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_retinanet,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_server_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_retinanet,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_server_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_retinanet,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_server_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_retinanet,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_server_) --> get,mlcommons,inference,src,_branch.master,_repo.https://github.com/mlcommons/inference
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src,_branch.master,_repo.https://github.com/mlcommons/inference
    app-mlperf-inference,d775cac873ee4231_(_reference,_retinanet,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_server_) --> get,mlperf,inference,utils
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_reference,_retinanet,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_server_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,cuda,_cudnn
    get-generic-python-lib,94b62a682bc44791_(_onnxruntime_gpu_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,generic-python-lib,_onnxruntime_gpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,ml-model,object-detection,retinanet,raw,_onnx,_fp32
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,dataset,object-detection,open-images,openimages,preprocessed,_validation,_NCHW,_full
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,python
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,sut,configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,mlcommons,inference,src,_branch.master,_repo.https://github.com/mlcommons/inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> generate,user-conf,mlperf,inference,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,loadgen,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,mlcommons,inference,src,_branch.master,_repo.https://github.com/mlcommons/inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_opencv-python_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,generic-python-lib,_opencv-python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,generic-sys-util,_libgl
    get-generic-python-lib,94b62a682bc44791_(_numpy_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,generic-python-lib,_numpy
    get-generic-python-lib,94b62a682bc44791_(_pycocotools_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_onnxruntime,_server,_retinanet,_fp32_) --> get,generic-python-lib,_pycocotools