graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_whisper,_vllm,_cpu,_valid,_r5.1-dev_default,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_whisper,_vllm,_cpu,_valid,_r5.1-dev_default,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_whisper,_vllm,_cpu,_valid,_r5.1-dev_default,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_whisper,_vllm,_cpu,_valid,_r5.1-dev_default,_offline_) --> get,mlcommons,inference,src,_repo.https://github.com/anandhu-eng/inference,_branch.whisper-fix
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src,_repo.https://github.com/anandhu-eng/inference,_branch.whisper-fix
    app-mlperf-inference,d775cac873ee4231_(_reference,_whisper,_vllm,_cpu,_valid,_r5.1-dev_default,_offline_) --> get,mlperf,inference,utils
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> install-vllm-from-src,_cpu
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,python
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,sut,configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,mlcommons,inference,src,_repo.https://github.com/anandhu-eng/inference,_branch.whisper-fix
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> generate,user-conf,mlperf,inference,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,loadgen,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,mlcommons,inference,src,_repo.https://github.com/anandhu-eng/inference,_branch.whisper-fix
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_package.py-libnuma_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,generic-python-lib,_package.py-libnuma
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,generic-sys-util,_libnuma-dev
    get-generic-python-lib,94b62a682bc44791_(_package.setuptools-scm_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,generic-python-lib,_package.setuptools-scm
    get-generic-python-lib,94b62a682bc44791_(_package.librosa_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,generic-python-lib,_package.librosa
    get-generic-python-lib,94b62a682bc44791_(_package.transformers_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,generic-python-lib,_package.transformers
    get-generic-python-lib,94b62a682bc44791_(_package.openai-whisper_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,generic-python-lib,_package.openai-whisper
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,ml-model,whisper,_rclone,_mlc
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cpu,_offline,_whisper,_vllm,_fp32_) --> get,dataset,whisper,_preprocessed,_mlc,_rclone