name: "mobile_vision.cls"
op {
  input: "data"
  input: "conv1_w"
  input: "res_conv1_bn_b"
  output: "res_conv1_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res_conv1_bn"
  output: "res_conv1_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res_conv1_bn"
  output: "pool1"
  name: ""
  type: "MaxPool"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pool1"
  input: "res2_0_branch2a_w"
  input: "res2_0_branch2a_bn_b"
  output: "res2_0_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_0_branch2a_bn"
  output: "res2_0_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2a_bn"
  output: "res2_0_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_branch2a_shuffle"
  input: "res2_0_branch2b_w"
  input: "res2_0_branch2b_bn_b"
  output: "res2_0_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 50
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_0_branch2b_bn"
  input: "res2_0_branch2c_w"
  input: "res2_0_branch2c_bn_b"
  output: "res2_0_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "pool1"
  output: "res2_0_pool_sc"
  name: ""
  type: "AveragePool"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_pool_sc"
  input: "res2_0_branch2c_bn"
  output: "res2_0_concat_sc"
  output: "res2_0_concat_sc_concat_"
  name: ""
  type: "Concat"
  arg {
    name: "axis"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_concat_sc"
  output: "res2_0_concat_sc"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_0_concat_sc"
  input: "res2_1_branch2a_w"
  input: "res2_1_branch2a_bn_b"
  output: "res2_1_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_1_branch2a_bn"
  output: "res2_1_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2a_bn"
  output: "res2_1_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2a_shuffle"
  input: "res2_1_branch2b_w"
  input: "res2_1_branch2b_bn_b"
  output: "res2_1_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 50
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_1_branch2b_bn"
  input: "res2_1_branch2c_w"
  input: "res2_1_branch2c_bn_b"
  output: "res2_1_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_1_branch2c_bn"
  input: "res2_0_concat_sc"
  output: "res2_1_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2c_bn"
  output: "res2_1_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_1_branch2c_bn"
  input: "res2_2_branch2a_w"
  input: "res2_2_branch2a_bn_b"
  output: "res2_2_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_2_branch2a_bn"
  output: "res2_2_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2a_bn"
  output: "res2_2_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2a_shuffle"
  input: "res2_2_branch2b_w"
  input: "res2_2_branch2b_bn_b"
  output: "res2_2_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 50
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_2_branch2b_bn"
  input: "res2_2_branch2c_w"
  input: "res2_2_branch2c_bn_b"
  output: "res2_2_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_2_branch2c_bn"
  input: "res2_1_branch2c_bn"
  output: "res2_2_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2c_bn"
  output: "res2_2_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_2_branch2c_bn"
  input: "res2_3_branch2a_w"
  input: "res2_3_branch2a_bn_b"
  output: "res2_3_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_3_branch2a_bn"
  output: "res2_3_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_3_branch2a_bn"
  output: "res2_3_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_3_branch2a_shuffle"
  input: "res2_3_branch2b_w"
  input: "res2_3_branch2b_bn_b"
  output: "res2_3_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 50
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_3_branch2b_bn"
  input: "res2_3_branch2c_w"
  input: "res2_3_branch2c_bn_b"
  output: "res2_3_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_3_branch2c_bn"
  input: "res2_2_branch2c_bn"
  output: "res2_3_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res2_3_branch2c_bn"
  output: "res2_3_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res2_3_branch2c_bn"
  input: "res3_0_branch2a_w"
  input: "res3_0_branch2a_bn_b"
  output: "res3_0_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_0_branch2a_bn"
  output: "res3_0_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2a_bn"
  output: "res3_0_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_branch2a_shuffle"
  input: "res3_0_branch2b_w"
  input: "res3_0_branch2b_bn_b"
  output: "res3_0_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_0_branch2b_bn"
  input: "res3_0_branch2c_w"
  input: "res3_0_branch2c_bn_b"
  output: "res3_0_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res2_3_branch2c_bn"
  output: "res3_0_pool_sc"
  name: ""
  type: "AveragePool"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_pool_sc"
  input: "res3_0_branch2c_bn"
  output: "res3_0_concat_sc"
  output: "res3_0_concat_sc_concat_"
  name: ""
  type: "Concat"
  arg {
    name: "axis"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_concat_sc"
  output: "res3_0_concat_sc"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_0_concat_sc"
  input: "res3_1_branch2a_w"
  input: "res3_1_branch2a_bn_b"
  output: "res3_1_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_1_branch2a_bn"
  output: "res3_1_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2a_bn"
  output: "res3_1_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2a_shuffle"
  input: "res3_1_branch2b_w"
  input: "res3_1_branch2b_bn_b"
  output: "res3_1_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_1_branch2b_bn"
  input: "res3_1_branch2c_w"
  input: "res3_1_branch2c_bn_b"
  output: "res3_1_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_1_branch2c_bn"
  input: "res3_0_concat_sc"
  output: "res3_1_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2c_bn"
  output: "res3_1_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_1_branch2c_bn"
  input: "res3_2_branch2a_w"
  input: "res3_2_branch2a_bn_b"
  output: "res3_2_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_2_branch2a_bn"
  output: "res3_2_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2a_bn"
  output: "res3_2_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2a_shuffle"
  input: "res3_2_branch2b_w"
  input: "res3_2_branch2b_bn_b"
  output: "res3_2_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_2_branch2b_bn"
  input: "res3_2_branch2c_w"
  input: "res3_2_branch2c_bn_b"
  output: "res3_2_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_2_branch2c_bn"
  input: "res3_1_branch2c_bn"
  output: "res3_2_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2c_bn"
  output: "res3_2_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_2_branch2c_bn"
  input: "res3_3_branch2a_w"
  input: "res3_3_branch2a_bn_b"
  output: "res3_3_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_3_branch2a_bn"
  output: "res3_3_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2a_bn"
  output: "res3_3_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2a_shuffle"
  input: "res3_3_branch2b_w"
  input: "res3_3_branch2b_bn_b"
  output: "res3_3_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_3_branch2b_bn"
  input: "res3_3_branch2c_w"
  input: "res3_3_branch2c_bn_b"
  output: "res3_3_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_3_branch2c_bn"
  input: "res3_2_branch2c_bn"
  output: "res3_3_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2c_bn"
  output: "res3_3_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_3_branch2c_bn"
  input: "res3_4_branch2a_w"
  input: "res3_4_branch2a_bn_b"
  output: "res3_4_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_4_branch2a_bn"
  output: "res3_4_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_4_branch2a_bn"
  output: "res3_4_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_4_branch2a_shuffle"
  input: "res3_4_branch2b_w"
  input: "res3_4_branch2b_bn_b"
  output: "res3_4_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_4_branch2b_bn"
  input: "res3_4_branch2c_w"
  input: "res3_4_branch2c_bn_b"
  output: "res3_4_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_4_branch2c_bn"
  input: "res3_3_branch2c_bn"
  output: "res3_4_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_4_branch2c_bn"
  output: "res3_4_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_4_branch2c_bn"
  input: "res3_5_branch2a_w"
  input: "res3_5_branch2a_bn_b"
  output: "res3_5_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_5_branch2a_bn"
  output: "res3_5_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_5_branch2a_bn"
  output: "res3_5_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_5_branch2a_shuffle"
  input: "res3_5_branch2b_w"
  input: "res3_5_branch2b_bn_b"
  output: "res3_5_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_5_branch2b_bn"
  input: "res3_5_branch2c_w"
  input: "res3_5_branch2c_bn_b"
  output: "res3_5_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_5_branch2c_bn"
  input: "res3_4_branch2c_bn"
  output: "res3_5_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_5_branch2c_bn"
  output: "res3_5_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_5_branch2c_bn"
  input: "res3_6_branch2a_w"
  input: "res3_6_branch2a_bn_b"
  output: "res3_6_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_6_branch2a_bn"
  output: "res3_6_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_6_branch2a_bn"
  output: "res3_6_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_6_branch2a_shuffle"
  input: "res3_6_branch2b_w"
  input: "res3_6_branch2b_bn_b"
  output: "res3_6_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_6_branch2b_bn"
  input: "res3_6_branch2c_w"
  input: "res3_6_branch2c_bn_b"
  output: "res3_6_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_6_branch2c_bn"
  input: "res3_5_branch2c_bn"
  output: "res3_6_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_6_branch2c_bn"
  output: "res3_6_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_6_branch2c_bn"
  input: "res3_7_branch2a_w"
  input: "res3_7_branch2a_bn_b"
  output: "res3_7_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_7_branch2a_bn"
  output: "res3_7_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_7_branch2a_bn"
  output: "res3_7_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_7_branch2a_shuffle"
  input: "res3_7_branch2b_w"
  input: "res3_7_branch2b_bn_b"
  output: "res3_7_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 100
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_7_branch2b_bn"
  input: "res3_7_branch2c_w"
  input: "res3_7_branch2c_bn_b"
  output: "res3_7_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_7_branch2c_bn"
  input: "res3_6_branch2c_bn"
  output: "res3_7_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res3_7_branch2c_bn"
  output: "res3_7_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res3_7_branch2c_bn"
  input: "res4_0_branch2a_w"
  input: "res4_0_branch2a_bn_b"
  output: "res4_0_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_0_branch2a_bn"
  output: "res4_0_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2a_bn"
  output: "res4_0_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_branch2a_shuffle"
  input: "res4_0_branch2b_w"
  input: "res4_0_branch2b_bn_b"
  output: "res4_0_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 200
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 2
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_0_branch2b_bn"
  input: "res4_0_branch2c_w"
  input: "res4_0_branch2c_bn_b"
  output: "res4_0_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res3_7_branch2c_bn"
  output: "res4_0_pool_sc"
  name: ""
  type: "AveragePool"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "stride"
    i: 2
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_pool_sc"
  input: "res4_0_branch2c_bn"
  output: "res4_0_concat_sc"
  output: "res4_0_concat_sc_concat_"
  name: ""
  type: "Concat"
  arg {
    name: "axis"
    i: 1
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_concat_sc"
  output: "res4_0_concat_sc"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_0_concat_sc"
  input: "res4_1_branch2a_w"
  input: "res4_1_branch2a_bn_b"
  output: "res4_1_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_1_branch2a_bn"
  output: "res4_1_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2a_bn"
  output: "res4_1_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2a_shuffle"
  input: "res4_1_branch2b_w"
  input: "res4_1_branch2b_bn_b"
  output: "res4_1_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 200
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_1_branch2b_bn"
  input: "res4_1_branch2c_w"
  input: "res4_1_branch2c_bn_b"
  output: "res4_1_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_1_branch2c_bn"
  input: "res4_0_concat_sc"
  output: "res4_1_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2c_bn"
  output: "res4_1_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_1_branch2c_bn"
  input: "res4_2_branch2a_w"
  input: "res4_2_branch2a_bn_b"
  output: "res4_2_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_2_branch2a_bn"
  output: "res4_2_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2a_bn"
  output: "res4_2_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2a_shuffle"
  input: "res4_2_branch2b_w"
  input: "res4_2_branch2b_bn_b"
  output: "res4_2_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 200
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_2_branch2b_bn"
  input: "res4_2_branch2c_w"
  input: "res4_2_branch2c_bn_b"
  output: "res4_2_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_2_branch2c_bn"
  input: "res4_1_branch2c_bn"
  output: "res4_2_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2c_bn"
  output: "res4_2_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_2_branch2c_bn"
  input: "res4_3_branch2a_w"
  input: "res4_3_branch2a_bn_b"
  output: "res4_3_branch2a_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_3_branch2a_bn"
  output: "res4_3_branch2a_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2a_bn"
  output: "res4_3_branch2a_shuffle"
  name: ""
  type: "ChannelShuffle"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2a_shuffle"
  input: "res4_3_branch2b_w"
  input: "res4_3_branch2b_bn_b"
  output: "res4_3_branch2b_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 3
  }
  arg {
    name: "pad"
    i: 1
  }
  arg {
    name: "group"
    i: 200
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "stride"
    i: 1
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_3_branch2b_bn"
  input: "res4_3_branch2c_w"
  input: "res4_3_branch2c_bn_b"
  output: "res4_3_branch2c_bn"
  name: ""
  type: "Conv"
  arg {
    name: "kernel"
    i: 1
  }
  arg {
    name: "group"
    i: 2
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  arg {
    name: "exhaustive_search"
    i: 1
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "pad"
    i: 0
  }
  arg {
    name: "order"
    s: "NCHW"
  }
  device_option {
  }
  engine: "DEPTHWISE_3x3,NNPACK"
}
op {
  input: "res4_3_branch2c_bn"
  input: "res4_2_branch2c_bn"
  output: "res4_3_branch2c_bn"
  name: ""
  type: "Sum"
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2c_bn"
  output: "res4_3_branch2c_bn"
  name: ""
  type: "Relu"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "res4_3_branch2c_bn"
  output: "pool5"
  name: ""
  type: "AveragePool"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "kernel"
    i: 7
  }
  arg {
    name: "stride"
    i: 1
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pool5"
  input: "pred_w"
  input: "pred_b"
  output: "pred"
  name: ""
  type: "FC"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
op {
  input: "pred"
  output: "softmax"
  name: ""
  type: "Softmax"
  arg {
    name: "order"
    s: "NCHW"
  }
  arg {
    name: "ws_nbytes_limit"
    i: 268435456
  }
  device_option {
  }
  engine: ""
}
external_input: "data"
external_input: "conv1_w"
external_input: "res_conv1_bn_b"
external_input: "res2_0_branch2a_w"
external_input: "res2_0_branch2a_bn_b"
external_input: "res2_0_branch2b_w"
external_input: "res2_0_branch2b_bn_b"
external_input: "res2_0_branch2c_w"
external_input: "res2_0_branch2c_bn_b"
external_input: "res2_1_branch2a_w"
external_input: "res2_1_branch2a_bn_b"
external_input: "res2_1_branch2b_w"
external_input: "res2_1_branch2b_bn_b"
external_input: "res2_1_branch2c_w"
external_input: "res2_1_branch2c_bn_b"
external_input: "res2_2_branch2a_w"
external_input: "res2_2_branch2a_bn_b"
external_input: "res2_2_branch2b_w"
external_input: "res2_2_branch2b_bn_b"
external_input: "res2_2_branch2c_w"
external_input: "res2_2_branch2c_bn_b"
external_input: "res2_3_branch2a_w"
external_input: "res2_3_branch2a_bn_b"
external_input: "res2_3_branch2b_w"
external_input: "res2_3_branch2b_bn_b"
external_input: "res2_3_branch2c_w"
external_input: "res2_3_branch2c_bn_b"
external_input: "res3_0_branch2a_w"
external_input: "res3_0_branch2a_bn_b"
external_input: "res3_0_branch2b_w"
external_input: "res3_0_branch2b_bn_b"
external_input: "res3_0_branch2c_w"
external_input: "res3_0_branch2c_bn_b"
external_input: "res3_1_branch2a_w"
external_input: "res3_1_branch2a_bn_b"
external_input: "res3_1_branch2b_w"
external_input: "res3_1_branch2b_bn_b"
external_input: "res3_1_branch2c_w"
external_input: "res3_1_branch2c_bn_b"
external_input: "res3_2_branch2a_w"
external_input: "res3_2_branch2a_bn_b"
external_input: "res3_2_branch2b_w"
external_input: "res3_2_branch2b_bn_b"
external_input: "res3_2_branch2c_w"
external_input: "res3_2_branch2c_bn_b"
external_input: "res3_3_branch2a_w"
external_input: "res3_3_branch2a_bn_b"
external_input: "res3_3_branch2b_w"
external_input: "res3_3_branch2b_bn_b"
external_input: "res3_3_branch2c_w"
external_input: "res3_3_branch2c_bn_b"
external_input: "res3_4_branch2a_w"
external_input: "res3_4_branch2a_bn_b"
external_input: "res3_4_branch2b_w"
external_input: "res3_4_branch2b_bn_b"
external_input: "res3_4_branch2c_w"
external_input: "res3_4_branch2c_bn_b"
external_input: "res3_5_branch2a_w"
external_input: "res3_5_branch2a_bn_b"
external_input: "res3_5_branch2b_w"
external_input: "res3_5_branch2b_bn_b"
external_input: "res3_5_branch2c_w"
external_input: "res3_5_branch2c_bn_b"
external_input: "res3_6_branch2a_w"
external_input: "res3_6_branch2a_bn_b"
external_input: "res3_6_branch2b_w"
external_input: "res3_6_branch2b_bn_b"
external_input: "res3_6_branch2c_w"
external_input: "res3_6_branch2c_bn_b"
external_input: "res3_7_branch2a_w"
external_input: "res3_7_branch2a_bn_b"
external_input: "res3_7_branch2b_w"
external_input: "res3_7_branch2b_bn_b"
external_input: "res3_7_branch2c_w"
external_input: "res3_7_branch2c_bn_b"
external_input: "res4_0_branch2a_w"
external_input: "res4_0_branch2a_bn_b"
external_input: "res4_0_branch2b_w"
external_input: "res4_0_branch2b_bn_b"
external_input: "res4_0_branch2c_w"
external_input: "res4_0_branch2c_bn_b"
external_input: "res4_1_branch2a_w"
external_input: "res4_1_branch2a_bn_b"
external_input: "res4_1_branch2b_w"
external_input: "res4_1_branch2b_bn_b"
external_input: "res4_1_branch2c_w"
external_input: "res4_1_branch2c_bn_b"
external_input: "res4_2_branch2a_w"
external_input: "res4_2_branch2a_bn_b"
external_input: "res4_2_branch2b_w"
external_input: "res4_2_branch2b_bn_b"
external_input: "res4_2_branch2c_w"
external_input: "res4_2_branch2c_bn_b"
external_input: "res4_3_branch2a_w"
external_input: "res4_3_branch2a_bn_b"
external_input: "res4_3_branch2b_w"
external_input: "res4_3_branch2b_bn_b"
external_input: "res4_3_branch2c_w"
external_input: "res4_3_branch2c_bn_b"
external_input: "pred_w"
external_input: "pred_b"
external_output: "softmax"
