#!/usr/bin/env python3
"""Download the 470 additional Wikipedia HTML files.

This script is self-contained: the URL list is embedded below. Pass the output
folder as the only command-line argument; files are written directly there.
"""

from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path
import argparse
import json
import time
import urllib.error
import urllib.request

WORKERS = 8
USER_AGENT = "Mozilla/5.0 (compatible; html-fetch/1.0)"

DOWNLOADS = [('en.wikipedia.org_wiki_%22Weird_Al%22_Yankovic.html', 'https://en.wikipedia.org/wiki/%22Weird_Al%22_Yankovic'),
 ('en.wikipedia.org_wiki_%C5%BDAK_Subotica.html', 'https://en.wikipedia.org/wiki/%C5%BDAK_Subotica'),
 ('en.wikipedia.org_wiki_1854_Broad_Street_cholera_outbreak#.html',
  'https://en.wikipedia.org/wiki/1854_Broad_Street_cholera_outbreak#'),
 ('en.wikipedia.org_wiki_1900%E2%80%9301_Football_League#Final_league_tables.html',
  'https://en.wikipedia.org/wiki/1900%E2%80%9301_Football_League#Final_league_tables'),
 ('en.wikipedia.org_wiki_1923#Deaths.html', 'https://en.wikipedia.org/wiki/1923#Deaths'),
 ('en.wikipedia.org_wiki_1960_European_Nations%27_Cup.html',
  'https://en.wikipedia.org/wiki/1960_European_Nations%27_Cup'),
 ('en.wikipedia.org_wiki_1967_Formula_One_season#Teams_and_drivers.html',
  'https://en.wikipedia.org/wiki/1967_Formula_One_season#Teams_and_drivers'),
 ('en.wikipedia.org_wiki_1972#.html', 'https://en.wikipedia.org/wiki/1972#'),
 ('en.wikipedia.org_wiki_1976%E2%80%9377_Portland_Trail_Blazers_season.html',
  'https://en.wikipedia.org/wiki/1976%E2%80%9377_Portland_Trail_Blazers_season'),
 ('en.wikipedia.org_wiki_1982%E2%80%9383_Wolverhampton_Wanderers_F.C._season.html',
  'https://en.wikipedia.org/wiki/1982%E2%80%9383_Wolverhampton_Wanderers_F.C._season'),
 ('en.wikipedia.org_wiki_1984%E2%80%9385_NHL_season.html', 'https://en.wikipedia.org/wiki/1984%E2%80%9385_NHL_season'),
 ('en.wikipedia.org_wiki_1996%E2%80%9397_AC_Milan_season.html',
  'https://en.wikipedia.org/wiki/1996%E2%80%9397_AC_Milan_season'),
 ('en.wikipedia.org_wiki_1996%E2%80%9397_Detroit_Red_Wings_season.html',
  'https://en.wikipedia.org/wiki/1996%E2%80%9397_Detroit_Red_Wings_season'),
 ('en.wikipedia.org_wiki_1997_NFL_draft#Round_6.html', 'https://en.wikipedia.org/wiki/1997_NFL_draft#Round_6'),
 ('en.wikipedia.org_wiki_1998_NFL_draft#Player_selections.html',
  'https://en.wikipedia.org/wiki/1998_NFL_draft#Player_selections'),
 ('en.wikipedia.org_wiki_1999%E2%80%932000_Olympique_de_Marseille_season.html',
  'https://en.wikipedia.org/wiki/1999%E2%80%932000_Olympique_de_Marseille_season'),
 ('en.wikipedia.org_wiki_19th_People%27s_Choice_Awards#Awards.html',
  'https://en.wikipedia.org/wiki/19th_People%27s_Choice_Awards#Awards'),
 ('en.wikipedia.org_wiki_2002_Wimbledon_Championships_%E2%80%93_Men%27s_singles.html',
  'https://en.wikipedia.org/wiki/2002_Wimbledon_Championships_%E2%80%93_Men%27s_singles'),
 ('en.wikipedia.org_wiki_2002_World_Series#Composite_box.html',
  'https://en.wikipedia.org/wiki/2002_World_Series#Composite_box'),
 ('en.wikipedia.org_wiki_2003_US_Open_%E2%80%93_Men%27s_singles.html',
  'https://en.wikipedia.org/wiki/2003_US_Open_%E2%80%93_Men%27s_singles'),
 ('en.wikipedia.org_wiki_2006_Nobel_Prize_in_Literature#_~_text=The%202006%20Nobel%20Prize%20in,clash%20and%20interlacing%20of%20cultures.%22.html',
  'https://en.wikipedia.org/wiki/2006_Nobel_Prize_in_Literature#_~_text=The%202006%20Nobel%20Prize%20in,clash%20and%20interlacing%20of%20cultures.%22'),
 ('en.wikipedia.org_wiki_2006_Nobel_Prize_in_Literature#_~_text=The%202006%20Nobel%20Prize%20in.html',
  'https://en.wikipedia.org/wiki/2006_Nobel_Prize_in_Literature#_~_text=The%202006%20Nobel%20Prize%20in'),
 ('en.wikipedia.org_wiki_2007_NHL_entry_draft#Round_one.html',
  'https://en.wikipedia.org/wiki/2007_NHL_entry_draft#Round_one'),
 ('en.wikipedia.org_wiki_2011_T%C5%8Dhoku_earthquake_and_tsunami#Nuclear_power_plants.html',
  'https://en.wikipedia.org/wiki/2011_T%C5%8Dhoku_earthquake_and_tsunami#Nuclear_power_plants'),
 ('en.wikipedia.org_wiki_2011_T%C5%8Dhoku_earthquake_and_tsunami.html',
  'https://en.wikipedia.org/wiki/2011_T%C5%8Dhoku_earthquake_and_tsunami'),
 ('en.wikipedia.org_wiki_2013%E2%80%9314_Portland_Trail_Blazers_season#Playoffs.html',
  'https://en.wikipedia.org/wiki/2013%E2%80%9314_Portland_Trail_Blazers_season#Playoffs'),
 ('en.wikipedia.org_wiki_2015_FIFA_Women%27s_World_Cup_knockout_stage.html',
  'https://en.wikipedia.org/wiki/2015_FIFA_Women%27s_World_Cup_knockout_stage'),
 ('en.wikipedia.org_wiki_2015_World_Championships_in_Athletics_%E2%80%93_Women%27s_javelin_throw.html',
  'https://en.wikipedia.org/wiki/2015_World_Championships_in_Athletics_%E2%80%93_Women%27s_javelin_throw'),
 ('en.wikipedia.org_wiki_2016_Australian_Open_%E2%80%93_Men%27s_singles.html',
  'https://en.wikipedia.org/wiki/2016_Australian_Open_%E2%80%93_Men%27s_singles'),
 ('en.wikipedia.org_wiki_2016_CONCACAF_Women%27s_Olympic_Qualifying_Championship#Group_A.html',
  'https://en.wikipedia.org/wiki/2016_CONCACAF_Women%27s_Olympic_Qualifying_Championship#Group_A'),
 ('en.wikipedia.org_wiki_2018%E2%80%9319_Brisbane_Roar_FC_season.html',
  'https://en.wikipedia.org/wiki/2018%E2%80%9319_Brisbane_Roar_FC_season'),
 ('en.wikipedia.org_wiki_2018%E2%80%9319_Women%27s_Volleyball_Thailand_League.html',
  'https://en.wikipedia.org/wiki/2018%E2%80%9319_Women%27s_Volleyball_Thailand_League'),
 ('en.wikipedia.org_wiki_2018_FIFA_World_Cup#Officiating.html',
  'https://en.wikipedia.org/wiki/2018_FIFA_World_Cup#Officiating'),
 ('en.wikipedia.org_wiki_2019%E2%80%9320_NBA_season.html', 'https://en.wikipedia.org/wiki/2019%E2%80%9320_NBA_season'),
 ('en.wikipedia.org_wiki_2020%E2%80%9321_Dallas_Mavericks_season.html',
  'https://en.wikipedia.org/wiki/2020%E2%80%9321_Dallas_Mavericks_season'),
 ('en.wikipedia.org_wiki_2020%E2%80%9321_NBA_season.html', 'https://en.wikipedia.org/wiki/2020%E2%80%9321_NBA_season'),
 ('en.wikipedia.org_wiki_2021_French_Open_%E2%80%93_Men%2527s_singles.html',
  'https://en.wikipedia.org/wiki/2021_French_Open_%E2%80%93_Men%27s_singles'),
 ('en.wikipedia.org_wiki_2024_Yucat%C3%A1n_Open_%E2%80%93_Doubles.html',
  'https://en.wikipedia.org/wiki/2024_Yucat%C3%A1n_Open_%E2%80%93_Doubles'),
 ('en.wikipedia.org_wiki_74th_Academy_Awards#Winners_and_nominees.html',
  'https://en.wikipedia.org/wiki/74th_Academy_Awards#Winners_and_nominees'),
 ('en.wikipedia.org_wiki_95th_Academy_Awards#Awards.html', 'https://en.wikipedia.org/wiki/95th_Academy_Awards#Awards'),
 ('en.wikipedia.org_wiki_AC_DC_discography#Live_albums.html',
  'https://en.wikipedia.org/wiki/AC/DC_discography#Live_albums'),
 ('en.wikipedia.org_wiki_A_Brooklyn_State_of_Mind#Cast.html',
  'https://en.wikipedia.org/wiki/A_Brooklyn_State_of_Mind#Cast'),
 ('en.wikipedia.org_wiki_Academy_Award_for_Best_Actor#1960s.html',
  'https://en.wikipedia.org/wiki/Academy_Award_for_Best_Actor#1960s'),
 ('en.wikipedia.org_wiki_Academy_Award_for_Best_Animated_Feature#Multiple_wins_and_nominations.html',
  'https://en.wikipedia.org/wiki/Academy_Award_for_Best_Animated_Feature#Multiple_wins_and_nominations'),
 ('en.wikipedia.org_wiki_Academy_Award_for_Best_Picture#1970s.html',
  'https://en.wikipedia.org/wiki/Academy_Award_for_Best_Picture#1970s'),
 ('en.wikipedia.org_wiki_Academy_of_Science.html', 'https://en.wikipedia.org/wiki/Academy_of_Science'),
 ('en.wikipedia.org_wiki_Albert_Bartholom%C3%A9#Main_works_(continued).html',
  'https://en.wikipedia.org/wiki/Albert_Bartholom%C3%A9#Main_works_(continued)'),
 ('en.wikipedia.org_wiki_Alberto_Gin%C3%A9s_L%C3%B3pez.html',
  'https://en.wikipedia.org/wiki/Alberto_Gin%C3%A9s_L%C3%B3pez'),
 ('en.wikipedia.org_wiki_Alex_Hern%C3%A1ndez_(tennis).html',
  'https://en.wikipedia.org/wiki/Alex_Hern%C3%A1ndez_(tennis)'),
 ('en.wikipedia.org_wiki_Alexis_Clairaut#Focus_on_astronomical_motion.html',
  'https://en.wikipedia.org/wiki/Alexis_Clairaut#Focus_on_astronomical_motion'),
 ('en.wikipedia.org_wiki_American_Athletic_Conference_Men%27s_Basketball_Player_of_the_Year.html',
  'https://en.wikipedia.org/wiki/American_Athletic_Conference_Men%27s_Basketball_Player_of_the_Year'),
 ('en.wikipedia.org_wiki_Amplifier_(Dance_Exponents_album)#Track_listing.html',
  'https://en.wikipedia.org/wiki/Amplifier_(Dance_Exponents_album)#Track_listing'),
 ('en.wikipedia.org_wiki_Andhra_Pradesh_(1956%E2%80%932014).html',
  'https://en.wikipedia.org/wiki/Andhra_Pradesh_(1956%E2%80%932014)'),
 ('en.wikipedia.org_wiki_Andr%C3%A9_the_Giant.html', 'https://en.wikipedia.org/wiki/Andr%C3%A9_the_Giant'),
 ('en.wikipedia.org_wiki_André_Silva_(footballer.html', 'https://en.wikipedia.org/wiki/Andr%C3%A9_Silva_(footballer)'),
 ('en.wikipedia.org_wiki_Andy_Roddick_career_statistics#Singles__5_finals_(1–4).html',
  'https://en.wikipedia.org/wiki/Andy_Roddick_career_statistics#Singles__5_finals_(1%E2%80%934)'),
 ('en.wikipedia.org_wiki_Anna_Stre%C5%BCy%C5%84ska.html', 'https://en.wikipedia.org/wiki/Anna_Stre%C5%BCy%C5%84ska'),
 ('en.wikipedia.org_wiki_Anne.html', 'https://en.wikipedia.org/wiki/Anne'),
 ('en.wikipedia.org_wiki_Apollo_11#Mission.html', 'https://en.wikipedia.org/wiki/Apollo_11#Mission'),
 ('en.wikipedia.org_wiki_Archibald_Sinclair.html', 'https://en.wikipedia.org/wiki/Archibald_Sinclair'),
 ('en.wikipedia.org_wiki_Arctic_Ocean#Climate.html', 'https://en.wikipedia.org/wiki/Arctic_Ocean#Climate'),
 ('en.wikipedia.org_wiki_Argentina_at_the_FIFA_World_Cup#_~_text=Argentina%20is%20one%20of%20the,in%201930%2C%201990%20and%202014..html',
  'https://en.wikipedia.org/wiki/Argentina_at_the_FIFA_World_Cup#_~_text=Argentina%20is%20one%20of%20the,in%201930%2C%201990%20and%202014.'),
 ('en.wikipedia.org_wiki_Argentina_at_the_FIFA_World_Cup#_~_text=Argentina%20is%20one%20of%20the.html',
  'https://en.wikipedia.org/wiki/Argentina_at_the_FIFA_World_Cup#_~_text=Argentina%20is%20one%20of%20the'),
 ('en.wikipedia.org_wiki_Arlington.html', 'https://en.wikipedia.org/wiki/Arlington'),
 ('en.wikipedia.org_wiki_Auckland_Island#Human_presence_on_the_island.html',
  'https://en.wikipedia.org/wiki/Auckland_Island#Human_presence_on_the_island'),
 ('en.wikipedia.org_wiki_August_16#1901%E2%80%93present_2.html',
  'https://en.wikipedia.org/wiki/August_16#1901%E2%80%93present_2'),
 ('en.wikipedia.org_wiki_Avalokite%C5%9Bvara.html', 'https://en.wikipedia.org/wiki/Avalokite%C5%9Bvara'),
 ('en.wikipedia.org_wiki_Avukana_Buddha_statue#Location_and_appearance.html',
  'https://en.wikipedia.org/wiki/Avukana_Buddha_statue#Location_and_appearance'),
 ('en.wikipedia.org_wiki_BTS#.html', 'https://en.wikipedia.org/wiki/BTS#'),
 ('en.wikipedia.org_wiki_Baby_Vox#Studio_albums.html', 'https://en.wikipedia.org/wiki/Baby_Vox#Studio_albums'),
 ('en.wikipedia.org_wiki_Baldur%27s_Gate_3#.html', 'https://en.wikipedia.org/wiki/Baldur%27s_Gate_3#'),
 ('en.wikipedia.org_wiki_Balliol_College.html', 'https://en.wikipedia.org/wiki/Balliol_College'),
 ('en.wikipedia.org_wiki_Bath,_Somerset#Culture.html', 'https://en.wikipedia.org/wiki/Bath,_Somerset#Culture'),
 ('en.wikipedia.org_wiki_Bath.html', 'https://en.wikipedia.org/wiki/Bath'),
 ('en.wikipedia.org_wiki_Bernhard_von_B%C3%BClow.html', 'https://en.wikipedia.org/wiki/Bernhard_von_B%C3%BClow'),
 ('en.wikipedia.org_wiki_Bessemer.html', 'https://en.wikipedia.org/wiki/Bessemer'),
 ('en.wikipedia.org_wiki_Beyonc%C3%A9#.html', 'https://en.wikipedia.org/wiki/Beyonc%C3%A9#'),
 ('en.wikipedia.org_wiki_Big_Ben#Design.html', 'https://en.wikipedia.org/wiki/Big_Ben#Design'),
 ('en.wikipedia.org_wiki_Big_Hit_Music#Groups.html', 'https://en.wikipedia.org/wiki/Big_Hit_Music#Groups'),
 ('en.wikipedia.org_wiki_Billboard_Year-End_Hot_100_singles_of_1985#_~_text=Article,11.html',
  'https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1985#_~_text=Article,11'),
 ('en.wikipedia.org_wiki_Billboard_Year-End_Hot_100_singles_of_1985#_~_text=Article.html',
  'https://en.wikipedia.org/wiki/Billboard_Year-End_Hot_100_singles_of_1985#_~_text=Article'),
 ('en.wikipedia.org_wiki_Bird#Anatomy_and_physiology.html',
  'https://en.wikipedia.org/wiki/Bird#Anatomy_and_physiology'),
 ('en.wikipedia.org_wiki_Birut%C4%97_Galdikas.html', 'https://en.wikipedia.org/wiki/Birut%C4%97_Galdikas'),
 ('en.wikipedia.org_wiki_Blink-182#Tours.html', 'https://en.wikipedia.org/wiki/Blink-182#Tours'),
 ('en.wikipedia.org_wiki_Blue_moon#Blue_moon_dates.html', 'https://en.wikipedia.org/wiki/Blue_moon#Blue_moon_dates'),
 ('en.wikipedia.org_wiki_Blyde_River_Canyon_Nature_Reserve#God.27s_Window.html',
  'https://en.wikipedia.org/wiki/Blyde_River_Canyon_Nature_Reserve#God.27s_Window'),
 ('en.wikipedia.org_wiki_BoA#Discography.html', 'https://en.wikipedia.org/wiki/BoA#Discography'),
 ('en.wikipedia.org_wiki_Boston_Marathon#Rosie_Ruiz,_the_impostor.html',
  'https://en.wikipedia.org/wiki/Boston_Marathon#Rosie_Ruiz,_the_impostor'),
 ('en.wikipedia.org_wiki_Boston_Marathon#Rosie_Ruiz.html', 'https://en.wikipedia.org/wiki/Boston_Marathon#Rosie_Ruiz'),
 ("en.wikipedia.org_wiki_Bowling_at_the_2011_Pan_American_Games_%E2%80%93_Women's_individual.html",
  "https://en.wikipedia.org/wiki/Bowling_at_the_2011_Pan_American_Games_%E2%80%93_Women's_individual"),
 ('en.wikipedia.org_wiki_Brazil_national_football_team#FIFA_World_Cup.html',
  'https://en.wikipedia.org/wiki/Brazil_national_football_team#FIFA_World_Cup'),
 ('en.wikipedia.org_wiki_Bridgeton.html', 'https://en.wikipedia.org/wiki/Bridgeton'),
 ('en.wikipedia.org_wiki_Britain%27s_Got_Talent.html', 'https://en.wikipedia.org/wiki/Britain%27s_Got_Talent'),
 ('en.wikipedia.org_wiki_Bro%27Town.html', 'https://en.wikipedia.org/wiki/Bro%27Town'),
 ('en.wikipedia.org_wiki_Broken_Arrow.html', 'https://en.wikipedia.org/wiki/Broken_Arrow'),
 ('en.wikipedia.org_wiki_Bront%C3%AB_family.html', 'https://en.wikipedia.org/wiki/Bront%C3%AB_family'),
 ('en.wikipedia.org_wiki_Brown_County.html', 'https://en.wikipedia.org/wiki/Brown_County'),
 ('en.wikipedia.org_wiki_C%27%C3%A8_la_luna_mezzo_mare#Notable_recordings.html',
  'https://en.wikipedia.org/wiki/C%27%C3%A8_la_luna_mezzo_mare#Notable_recordings'),
 ('en.wikipedia.org_wiki_Caldecott_Medal#Recipients.html', 'https://en.wikipedia.org/wiki/Caldecott_Medal#Recipients'),
 ('en.wikipedia.org_wiki_Call_Me_Maybe#Year-end_charts.html',
  'https://en.wikipedia.org/wiki/Call_Me_Maybe#Year-end_charts'),
 ('en.wikipedia.org_wiki_Calton.html', 'https://en.wikipedia.org/wiki/Calton'),
 ('en.wikipedia.org_wiki_Capybara#.html', 'https://en.wikipedia.org/wiki/Capybara#'),
 ('en.wikipedia.org_wiki_Carola_H%C3%A4ggkvist.html', 'https://en.wikipedia.org/wiki/Carola_H%C3%A4ggkvist'),
 ('en.wikipedia.org_wiki_Charley%27s_Aunt.html', 'https://en.wikipedia.org/wiki/Charley%27s_Aunt'),
 ('en.wikipedia.org_wiki_Charlotte_Bront%C3%AB.html', 'https://en.wikipedia.org/wiki/Charlotte_Bront%C3%AB'),
 ('en.wikipedia.org_wiki_Charlotte_Checkers_(1956%E2%80%931977).html',
  'https://en.wikipedia.org/wiki/Charlotte_Checkers_(1956%E2%80%931977)'),
 ('en.wikipedia.org_wiki_Chemotherapy#History.html', 'https://en.wikipedia.org/wiki/Chemotherapy#History'),
 ('en.wikipedia.org_wiki_Cheyenne.html', 'https://en.wikipedia.org/wiki/Cheyenne'),
 ('en.wikipedia.org_wiki_Chikhali.html', 'https://en.wikipedia.org/wiki/Chikhali'),
 ('en.wikipedia.org_wiki_Chris_Benoit#Death.html', 'https://en.wikipedia.org/wiki/Chris_Benoit#Death'),
 ('en.wikipedia.org_wiki_Chris_Columbus_(filmmaker)#Filmography.html',
  'https://en.wikipedia.org/wiki/Chris_Columbus_(filmmaker)#Filmography'),
 ('en.wikipedia.org_wiki_Christie%27s.html', 'https://en.wikipedia.org/wiki/Christie%27s'),
 ('en.wikipedia.org_wiki_Cinthia_Pi%C3%B1eiro#.html', 'https://en.wikipedia.org/wiki/Cinthia_Pi%C3%B1eiro#'),
 ('en.wikipedia.org_wiki_Confucius#.html', 'https://en.wikipedia.org/wiki/Confucius#'),
 ('en.wikipedia.org_wiki_Cotton_gin#_~_text=A%20cotton%20gin%E2%80%94meaning%20%22cotton,productivity%20than%20manual%20cotton%20separation..html',
  'https://en.wikipedia.org/wiki/Cotton_gin#_~_text=A%20cotton%20gin%E2%80%94meaning%20%22cotton,productivity%20than%20manual%20cotton%20separation.'),
 ('en.wikipedia.org_wiki_Cotton_gin#_~_text=A%20cotton%20gin%E2%80%94meaning%20%22cotton.html',
  'https://en.wikipedia.org/wiki/Cotton_gin#_~_text=A%20cotton%20gin%E2%80%94meaning%20%22cotton'),
 ('en.wikipedia.org_wiki_Cowboy_Bebop__Knockin%27_on_Heaven%27s_Door.html',
  'https://en.wikipedia.org/wiki/Cowboy_Bebop:_Knockin%27_on_Heaven%27s_Door'),
 ('en.wikipedia.org_wiki_Cricket#Governance.html', 'https://en.wikipedia.org/wiki/Cricket#Governance'),
 ('en.wikipedia.org_wiki_Croix_de_guerre_1914%E2%80%931918_(France)#Award_description.html',
  'https://en.wikipedia.org/wiki/Croix_de_guerre_1914%E2%80%931918_(France)#Award_description'),
 ('en.wikipedia.org_wiki_Crossroads_(2002_film)#Reception.html',
  'https://en.wikipedia.org/wiki/Crossroads_(2002_film)#Reception'),
 ('en.wikipedia.org_wiki_Danny_DeVito#Acting_credits_and_accolades.html',
  'https://en.wikipedia.org/wiki/Danny_DeVito#Acting_credits_and_accolades'),
 ('en.wikipedia.org_wiki_Dax_Shepard#Film.html', 'https://en.wikipedia.org/wiki/Dax_Shepard#Film'),
 ('en.wikipedia.org_wiki_Derek_Smith_(footballer.html', 'https://en.wikipedia.org/wiki/Derek_Smith_(footballer)'),
 ('en.wikipedia.org_wiki_Devil%27s_Pass.html', 'https://en.wikipedia.org/wiki/Devil%27s_Pass'),
 ('en.wikipedia.org_wiki_Dhatusena_of_Anuradhapura#Early_life_and_becoming_king.html',
  'https://en.wikipedia.org/wiki/Dhatusena_of_Anuradhapura#Early_life_and_becoming_king'),
 ('en.wikipedia.org_wiki_Diana.html', 'https://en.wikipedia.org/wiki/Diana'),
 ('en.wikipedia.org_wiki_Didier_Drogba#Honours.html', 'https://en.wikipedia.org/wiki/Didier_Drogba#Honours'),
 ('en.wikipedia.org_wiki_Diego_Costa#Spain.html', 'https://en.wikipedia.org/wiki/Diego_Costa#Spain'),
 ('en.wikipedia.org_wiki_Diego_L%C3%B3pez_V_de_Haro.html', 'https://en.wikipedia.org/wiki/Diego_L%C3%B3pez_V_de_Haro'),
 ('en.wikipedia.org_wiki_Dippin%27_Dots.html', 'https://en.wikipedia.org/wiki/Dippin%27_Dots'),
 ('en.wikipedia.org_wiki_Disneynature#Filmography.html', 'https://en.wikipedia.org/wiki/Disneynature#Filmography'),
 ('en.wikipedia.org_wiki_Djokovic%E2%80%93Murray_rivalry.html',
  'https://en.wikipedia.org/wiki/Djokovic%E2%80%93Murray_rivalry'),
 ('en.wikipedia.org_wiki_Donahoe.html', 'https://en.wikipedia.org/wiki/Donahoe'),
 ('en.wikipedia.org_wiki_Dr._Quinn.html', 'https://en.wikipedia.org/wiki/Dr._Quinn'),
 ('en.wikipedia.org_wiki_Elon_Musk#Personal_life.html', 'https://en.wikipedia.org/wiki/Elon_Musk#Personal_life'),
 ('en.wikipedia.org_wiki_Emirates_(airline)#Services.html',
  'https://en.wikipedia.org/wiki/Emirates_(airline)#Services'),
 ('en.wikipedia.org_wiki_Emmanuel_Lubezki#Feature_film.html',
  'https://en.wikipedia.org/wiki/Emmanuel_Lubezki#Feature_film'),
 ('en.wikipedia.org_wiki_Emmy_Rossum#Awards_and_nominations.html',
  'https://en.wikipedia.org/wiki/Emmy_Rossum#Awards_and_nominations'),
 ('en.wikipedia.org_wiki_England#Geography.html', 'https://en.wikipedia.org/wiki/England#Geography'),
 ('en.wikipedia.org_wiki_Estadio_Jos%C3%A9_Mart%C3%ADn_Olaeta.html',
  'https://en.wikipedia.org/wiki/Estadio_Jos%C3%A9_Mart%C3%ADn_Olaeta'),
 ('en.wikipedia.org_wiki_Ethereum#Ether.html', 'https://en.wikipedia.org/wiki/Ethereum#Ether'),
 ('en.wikipedia.org_wiki_Fall_of_the_Berlin_Wall#_~_text=The%20fall%20of%20the%20Berlin,restrictions%20were%20overwhelmed%20and%20discarded..html',
  'https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall#_~_text=The%20fall%20of%20the%20Berlin,restrictions%20were%20overwhelmed%20and%20discarded.'),
 ('en.wikipedia.org_wiki_Fall_of_the_Berlin_Wall#_~_text=The%20fall%20of%20the%20Berlin.html',
  'https://en.wikipedia.org/wiki/Fall_of_the_Berlin_Wall#_~_text=The%20fall%20of%20the%20Berlin'),
 ('en.wikipedia.org_wiki_Fastest_animals#Fish.html', 'https://en.wikipedia.org/wiki/Fastest_animals#Fish'),
 ('en.wikipedia.org_wiki_Federative_units_of_Brazil#_media_File_Brazil,_administrative_divisions_(states)_-_en_-_colored.svg.html',
  'https://en.wikipedia.org/wiki/Federative_units_of_Brazil#_media_File_Brazil,_administrative_divisions_(states)_-_en_-_colored.svg'),
 ('en.wikipedia.org_wiki_Federative_units_of_Brazil#_media_File_Brazil.html',
  'https://en.wikipedia.org/wiki/Federative_units_of_Brazil#_media_File_Brazil'),
 ('en.wikipedia.org_wiki_Five_Nights_at_Freddy%27s.html', 'https://en.wikipedia.org/wiki/Five_Nights_at_Freddy%27s'),
 ('en.wikipedia.org_wiki_Fleetwood_Mac#Grammy_Awards.html',
  'https://en.wikipedia.org/wiki/Fleetwood_Mac#Grammy_Awards'),
 ('en.wikipedia.org_wiki_Flight_of_the_Earls#Journey.html',
  'https://en.wikipedia.org/wiki/Flight_of_the_Earls#Journey'),
 ('en.wikipedia.org_wiki_Florida_A%26M_University.html', 'https://en.wikipedia.org/wiki/Florida_A%26M_University'),
 ('en.wikipedia.org_wiki_Florida_Atlantic_Owls_men%27s_basketball.html',
  'https://en.wikipedia.org/wiki/Florida_Atlantic_Owls_men%27s_basketball'),
 ('en.wikipedia.org_wiki_For_Whom_the_Bell_Tolls#Pulitzer_Prize_snub.html',
  'https://en.wikipedia.org/wiki/For_Whom_the_Bell_Tolls#Pulitzer_Prize_snub'),
 ('en.wikipedia.org_wiki_Ford_Motor_Company#Sales_numbers.html',
  'https://en.wikipedia.org/wiki/Ford_Motor_Company#Sales_numbers'),
 ('en.wikipedia.org_wiki_Franz_Kafka#Stories.html', 'https://en.wikipedia.org/wiki/Franz_Kafka#Stories'),
 ('en.wikipedia.org_wiki_Friends_%26_Relatives.html', 'https://en.wikipedia.org/wiki/Friends_%26_Relatives'),
 ('en.wikipedia.org_wiki_G%C3%A9za_K%C3%A1das.html', 'https://en.wikipedia.org/wiki/G%C3%A9za_K%C3%A1das'),
 ('en.wikipedia.org_wiki_Galileo%27s_middle_finger#Exhibition_history.html',
  'https://en.wikipedia.org/wiki/Galileo%27s_middle_finger#Exhibition_history'),
 ('en.wikipedia.org_wiki_Garypidae#Genera.html', 'https://en.wikipedia.org/wiki/Garypidae#Genera'),
 ('en.wikipedia.org_wiki_Geffen_Records#History.html', 'https://en.wikipedia.org/wiki/Geffen_Records#History'),
 ('en.wikipedia.org_wiki_George_Harrison#Discography.html',
  'https://en.wikipedia.org/wiki/George_Harrison#Discography'),
 ('en.wikipedia.org_wiki_George_Howell_(entrepreneur)#The_Coffee_Connection.html',
  'https://en.wikipedia.org/wiki/George_Howell_(entrepreneur)#The_Coffee_Connection'),
 ('en.wikipedia.org_wiki_George_Talbot.html', 'https://en.wikipedia.org/wiki/George_Talbot'),
 ('en.wikipedia.org_wiki_George_Washington#Personal_life.html',
  'https://en.wikipedia.org/wiki/George_Washington#Personal_life'),
 ('en.wikipedia.org_wiki_Girl_Scouts_of_the_USA#Presidents.html',
  'https://en.wikipedia.org/wiki/Girl_Scouts_of_the_USA#Presidents'),
 ('en.wikipedia.org_wiki_Golden_Globe_Award_for_Best_Actor_in_a_Motion_Picture_%E2%80%93_Drama.html',
  'https://en.wikipedia.org/wiki/Golden_Globe_Award_for_Best_Actor_in_a_Motion_Picture_%E2%80%93_Drama'),
 ('en.wikipedia.org_wiki_Golden_Retriever#Health.html', 'https://en.wikipedia.org/wiki/Golden_Retriever#Health'),
 ('en.wikipedia.org_wiki_Goodbye.html', 'https://en.wikipedia.org/wiki/Goodbye'),
 ('en.wikipedia.org_wiki_Gothic_Revival_architecture#Roots.html',
  'https://en.wikipedia.org/wiki/Gothic_Revival_architecture#Roots'),
 ('en.wikipedia.org_wiki_Grace%27s_High_Falls.html', 'https://en.wikipedia.org/wiki/Grace%27s_High_Falls'),
 ('en.wikipedia.org_wiki_Grammy_Award_for_Best_New_Artist#1960s.html',
  'https://en.wikipedia.org/wiki/Grammy_Award_for_Best_New_Artist#1960s'),
 ('en.wikipedia.org_wiki_Grammy_Award_for_Song_of_the_Year#2000s.html',
  'https://en.wikipedia.org/wiki/Grammy_Award_for_Song_of_the_Year#2000s'),
 ('en.wikipedia.org_wiki_Grand_Slam_(tennis)#.html', 'https://en.wikipedia.org/wiki/Grand_Slam_(tennis)#'),
 ('en.wikipedia.org_wiki_Grateful_Dead#Main_career_(1967–1995).html',
  'https://en.wikipedia.org/wiki/Grateful_Dead#Main_career_(1967%E2%80%931995)'),
 ('en.wikipedia.org_wiki_Grenoble#Population.html', 'https://en.wikipedia.org/wiki/Grenoble#Population'),
 ('en.wikipedia.org_wiki_Grover_Cleveland#_~_text=Stephen%20Grover%20Cleveland%20(March%2018,serve%20non%2Dconsecutive%20presidential%20terms..html',
  'https://en.wikipedia.org/wiki/Grover_Cleveland#_~_text=Stephen%20Grover%20Cleveland%20(March%2018,serve%20non%2Dconsecutive%20presidential%20terms.'),
 ('en.wikipedia.org_wiki_Grover_Cleveland#_~_text=Stephen%20Grover%20Cleveland%20(March%2018.html',
  'https://en.wikipedia.org/wiki/Grover_Cleveland#_~_text=Stephen%20Grover%20Cleveland%20(March%2018'),
 ('en.wikipedia.org_wiki_Gymnastics_at_the_1992_Summer_Olympics_%E2%80%93_Women%27s_artistic_team_all-around.html',
  'https://en.wikipedia.org/wiki/Gymnastics_at_the_1992_Summer_Olympics_%E2%80%93_Women%27s_artistic_team_all-around'),
 ('en.wikipedia.org_wiki_H%C3%A4n.html', 'https://en.wikipedia.org/wiki/H%C3%A4n'),
 ('en.wikipedia.org_wiki_H%C3%B4tel_Matignon.html', 'https://en.wikipedia.org/wiki/H%C3%B4tel_Matignon'),
 ('en.wikipedia.org_wiki_Halley%27s_Comet.html', 'https://en.wikipedia.org/wiki/Halley%27s_Comet'),
 ('en.wikipedia.org_wiki_Hans_Zimmer#Grammy_Awards.html', 'https://en.wikipedia.org/wiki/Hans_Zimmer#Grammy_Awards'),
 ('en.wikipedia.org_wiki_Happy_Days#Characters.html', 'https://en.wikipedia.org/wiki/Happy_Days#Characters'),
 ('en.wikipedia.org_wiki_Harper%27s_Magazine.html', 'https://en.wikipedia.org/wiki/Harper%27s_Magazine'),
 ('en.wikipedia.org_wiki_Harry_Potter_and_the_Philosopher%27s_Stone.html',
  'https://en.wikipedia.org/wiki/Harry_Potter_and_the_Philosopher%27s_Stone'),
 ('en.wikipedia.org_wiki_Hatfield_College.html', 'https://en.wikipedia.org/wiki/Hatfield_College'),
 ('en.wikipedia.org_wiki_Hayao_Miyazaki#Views.html', 'https://en.wikipedia.org/wiki/Hayao_Miyazaki#Views'),
 ('en.wikipedia.org_wiki_Heaven%27s_Gate_(religious_group)#Nike_Decades.html',
  'https://en.wikipedia.org/wiki/Heaven%27s_Gate_(religious_group)#Nike_Decades'),
 ('en.wikipedia.org_wiki_Hemangiosarcoma#Treatments.html', 'https://en.wikipedia.org/wiki/Hemangiosarcoma#Treatments'),
 ('en.wikipedia.org_wiki_Hermann_G%C3%B6ring.html', 'https://en.wikipedia.org/wiki/Hermann_G%C3%B6ring'),
 ('en.wikipedia.org_wiki_Herzog_%26_de_Meuron.html', 'https://en.wikipedia.org/wiki/Herzog_%26_de_Meuron'),
 ('en.wikipedia.org_wiki_Hind%27s_Hall.html', 'https://en.wikipedia.org/wiki/Hind%27s_Hall'),
 ('en.wikipedia.org_wiki_Home_Alone_2__Lost_in_New_York#Cast.html',
  'https://en.wikipedia.org/wiki/Home_Alone_2:_Lost_in_New_York#Cast'),
 ('en.wikipedia.org_wiki_Hot_Rock_%26_Alternative_Songs.html',
  'https://en.wikipedia.org/wiki/Hot_Rock_%26_Alternative_Songs'),
 ('en.wikipedia.org_wiki_Hoxie.html', 'https://en.wikipedia.org/wiki/Hoxie'),
 ('en.wikipedia.org_wiki_Hudson%27s_Bay_Company.html', 'https://en.wikipedia.org/wiki/Hudson%27s_Bay_Company'),
 ('en.wikipedia.org_wiki_Hugh_Hefner#Early_life_and_education.html',
  'https://en.wikipedia.org/wiki/Hugh_Hefner#Early_life_and_education'),
 ('en.wikipedia.org_wiki_ICC_men%27s_player_rankings#Top_10_Test_batsmen.html',
  'https://en.wikipedia.org/wiki/ICC_men%27s_player_rankings#Top_10_Test_batsmen'),
 ('en.wikipedia.org_wiki_IPad#.html', 'https://en.wikipedia.org/wiki/IPad#'),
 ('en.wikipedia.org_wiki_IPhone_X#_~_text=The%20iPhone%20X%20(Roman%20numeral,released%20on%20November%203%2C%202017..html',
  'https://en.wikipedia.org/wiki/IPhone_X#_~_text=The%20iPhone%20X%20(Roman%20numeral,released%20on%20November%203%2C%202017.'),
 ('en.wikipedia.org_wiki_IPhone_X#_~_text=The%20iPhone%20X%20(Roman%20numeral.html',
  'https://en.wikipedia.org/wiki/IPhone_X#_~_text=The%20iPhone%20X%20(Roman%20numeral'),
 ('en.wikipedia.org_wiki_Ice_hockey_at_the_2010_Winter_Olympics_%E2%80%93_Men%27s_tournament.html',
  'https://en.wikipedia.org/wiki/Ice_hockey_at_the_2010_Winter_Olympics_%E2%80%93_Men%27s_tournament'),
 ('en.wikipedia.org_wiki_If_You_Want_Blood_You%27ve_Got_It.html',
  'https://en.wikipedia.org/wiki/If_You_Want_Blood_You%27ve_Got_It'),
 ('en.wikipedia.org_wiki_Iga_%C5%9Awi%C4%85tek.html', 'https://en.wikipedia.org/wiki/Iga_%C5%9Awi%C4%85tek'),
 ('en.wikipedia.org_wiki_Infinite_Jest#Adaptations.html', 'https://en.wikipedia.org/wiki/Infinite_Jest#Adaptations'),
 ('en.wikipedia.org_wiki_Interstate_94_in_Michigan#.html', 'https://en.wikipedia.org/wiki/Interstate_94_in_Michigan#'),
 ('en.wikipedia.org_wiki_Is%C3%A8re#Principal_towns.html', 'https://en.wikipedia.org/wiki/Is%C3%A8re#Principal_towns'),
 ('en.wikipedia.org_wiki_Istiklal_Mosque.html', 'https://en.wikipedia.org/wiki/Istiklal_Mosque'),
 ('en.wikipedia.org_wiki_It%27s_Always_Sunny_in_Philadelphia.html',
  'https://en.wikipedia.org/wiki/It%27s_Always_Sunny_in_Philadelphia'),
 ('en.wikipedia.org_wiki_Iv%C3%A1n_Rodr%C3%ADguez.html', 'https://en.wikipedia.org/wiki/Iv%C3%A1n_Rodr%C3%ADguez'),
 ('en.wikipedia.org_wiki_J%C3%BCrgen_Warnke.html', 'https://en.wikipedia.org/wiki/J%C3%BCrgen_Warnke'),
 ('en.wikipedia.org_wiki_Jackie_Robinson#.html', 'https://en.wikipedia.org/wiki/Jackie_Robinson#'),
 ('en.wikipedia.org_wiki_James_%22J.T.%22_Taylor.html', 'https://en.wikipedia.org/wiki/James_%22J.T.%22_Taylor'),
 ('en.wikipedia.org_wiki_James_Cameron#Filmography.html', 'https://en.wikipedia.org/wiki/James_Cameron#Filmography'),
 ('en.wikipedia.org_wiki_Jane_Austen#List_of_works.html', 'https://en.wikipedia.org/wiki/Jane_Austen#List_of_works'),
 ('en.wikipedia.org_wiki_Japanese_aircraft_carrier_Hiy%C5%8D.html',
  'https://en.wikipedia.org/wiki/Japanese_aircraft_carrier_Hiy%C5%8D'),
 ('en.wikipedia.org_wiki_Ji%C5%99%C3%AD_Bro%C5%BEek.html', 'https://en.wikipedia.org/wiki/Ji%C5%99%C3%AD_Bro%C5%BEek'),
 ('en.wikipedia.org_wiki_Jo%C3%ABl_Retornaz.html', 'https://en.wikipedia.org/wiki/Jo%C3%ABl_Retornaz'),
 ('en.wikipedia.org_wiki_Joe_Jonas#Personal_life.html', 'https://en.wikipedia.org/wiki/Joe_Jonas#Personal_life'),
 ('en.wikipedia.org_wiki_Joel_McHale#_~_text=Joel%20Edward%20McHale%20(born%20November,actor%2C%20comedian%20and%20television%20presenter..html',
  'https://en.wikipedia.org/wiki/Joel_McHale#_~_text=Joel%20Edward%20McHale%20(born%20November,actor%2C%20comedian%20and%20television%20presenter.'),
 ('en.wikipedia.org_wiki_Joel_McHale#_~_text=Joel%20Edward%20McHale%20(born%20November.html',
  'https://en.wikipedia.org/wiki/Joel_McHale#_~_text=Joel%20Edward%20McHale%20(born%20November'),
 ('en.wikipedia.org_wiki_John_Snow#.html', 'https://en.wikipedia.org/wiki/John_Snow#'),
 ('en.wikipedia.org_wiki_John_of_Lancaster.html', 'https://en.wikipedia.org/wiki/John_of_Lancaster'),
 ('en.wikipedia.org_wiki_Jonas_Brothers#Members.html', 'https://en.wikipedia.org/wiki/Jonas_Brothers#Members'),
 ('en.wikipedia.org_wiki_Jos%C3%A9_Loiola.html', 'https://en.wikipedia.org/wiki/Jos%C3%A9_Loiola'),
 ('en.wikipedia.org_wiki_Jos%C3%A9_Mar%C3%ADa_Arizmendiarrieta.html',
  'https://en.wikipedia.org/wiki/Jos%C3%A9_Mar%C3%ADa_Arizmendiarrieta'),
 ('en.wikipedia.org_wiki_José_Saramago#.html', 'https://en.wikipedia.org/wiki/Jos%C3%A9_Saramago#'),
 ('en.wikipedia.org_wiki_Juan_Gonz%C3%A1lez_(baseball).html',
  'https://en.wikipedia.org/wiki/Juan_Gonz%C3%A1lez_(baseball)'),
 ('en.wikipedia.org_wiki_Juneau.html', 'https://en.wikipedia.org/wiki/Juneau'),
 ('en.wikipedia.org_wiki_K%C5%8Dnan_Railway_K%C5%8Dnan_Line.html',
  'https://en.wikipedia.org/wiki/K%C5%8Dnan_Railway_K%C5%8Dnan_Line'),
 ('en.wikipedia.org_wiki_Kala_Wewa#History.html', 'https://en.wikipedia.org/wiki/Kala_Wewa#History'),
 ('en.wikipedia.org_wiki_Kelley_O%27Hara.html', 'https://en.wikipedia.org/wiki/Kelley_O%27Hara'),
 ('en.wikipedia.org_wiki_Kennebec_County.html', 'https://en.wikipedia.org/wiki/Kennebec_County'),
 ('en.wikipedia.org_wiki_Kente_cloth#cite_note-CNN-2020-06-08-18.html',
  'https://en.wikipedia.org/wiki/Kente_cloth#cite_note-CNN-2020-06-08-18'),
 ('en.wikipedia.org_wiki_Kevin_Jonas#Personal_life.html', 'https://en.wikipedia.org/wiki/Kevin_Jonas#Personal_life'),
 ('en.wikipedia.org_wiki_Key_West#_~_text=The%20southernmost%20location%20that%20the,apart%20at%20their%20closest%20points..html',
  'https://en.wikipedia.org/wiki/Key_West#_~_text=The%20southernmost%20location%20that%20the,apart%20at%20their%20closest%20points.'),
 ('en.wikipedia.org_wiki_Key_West#_~_text=The%20southernmost%20location%20that%20the.html',
  'https://en.wikipedia.org/wiki/Key_West#_~_text=The%20southernmost%20location%20that%20the'),
 ('en.wikipedia.org_wiki_Kill_%27Em_All.html', 'https://en.wikipedia.org/wiki/Kill_%27Em_All'),
 ('en.wikipedia.org_wiki_King%27s_Service_Medal.html', 'https://en.wikipedia.org/wiki/King%27s_Service_Medal'),
 ('en.wikipedia.org_wiki_Kundavai_Pir%C4%81ttiy%C4%81r.html',
  'https://en.wikipedia.org/wiki/Kundavai_Pir%C4%81ttiy%C4%81r'),
 ('en.wikipedia.org_wiki_LaMarcus_Aldridge#2013%E2%80%9314_season.html',
  'https://en.wikipedia.org/wiki/LaMarcus_Aldridge#2013%E2%80%9314_season'),
 ('en.wikipedia.org_wiki_La_Casita-Garciasville.html', 'https://en.wikipedia.org/wiki/La_Casita-Garciasville'),
 ('en.wikipedia.org_wiki_La_La_Land#Cast.html', 'https://en.wikipedia.org/wiki/La_La_Land#Cast'),
 ('en.wikipedia.org_wiki_La_Llorona#Literature.html', 'https://en.wikipedia.org/wiki/La_Llorona#Literature'),
 ('en.wikipedia.org_wiki_La_boh%C3%A8me.html', 'https://en.wikipedia.org/wiki/La_boh%C3%A8me'),
 ('en.wikipedia.org_wiki_Latrobe.html', 'https://en.wikipedia.org/wiki/Latrobe'),
 ('en.wikipedia.org_wiki_Laurentian_Library#Architecture.html',
  'https://en.wikipedia.org/wiki/Laurentian_Library#Architecture'),
 ('en.wikipedia.org_wiki_Lauryn_Hill#Early_life.html', 'https://en.wikipedia.org/wiki/Lauryn_Hill#Early_life'),
 ('en.wikipedia.org_wiki_Law_%26_Order__Special_Victims_Unit.html',
  'https://en.wikipedia.org/wiki/Law_%26_Order__Special_Victims_Unit'),
 ('en.wikipedia.org_wiki_Legion_of_Honour#Legal_status_and_leadership.html',
  'https://en.wikipedia.org/wiki/Legion_of_Honour#Legal_status_and_leadership'),
 ('en.wikipedia.org_wiki_Levi_Strauss_%26_Co.#Blue_jeans_era_(1960s%E2%80%931980s).html',
  'https://en.wikipedia.org/wiki/Levi_Strauss_%26_Co.#Blue_jeans_era_(1960s%E2%80%931980s)'),
 ('en.wikipedia.org_wiki_Life_%26_Casualty_Tower.html', 'https://en.wikipedia.org/wiki/Life_%26_Casualty_Tower'),
 ('en.wikipedia.org_wiki_Lincoln.html', 'https://en.wikipedia.org/wiki/Lincoln'),
 ('en.wikipedia.org_wiki_List_of_African-American_United_States_presidential_and_vice_presidential_candidates#_~_text=In%201848%2C%20Frederick%20Douglass%20became,major%20party%2C%20namely%20the%20Democr.html',
  'https://en.wikipedia.org/wiki/List_of_African-American_United_States_presidential_and_vice_presidential_candidates#_~_text=In%201848%2C%20Frederick%20Douglass%20became,major%20party%2C%20namely%20the%20Democr'),
 ('en.wikipedia.org_wiki_List_of_African-American_United_States_presidential_and_vice_presidential_candidates#_~_text=In%201848%2C%20Frederick%20Douglass%20became.html',
  'https://en.wikipedia.org/wiki/List_of_African-American_United_States_presidential_and_vice_presidential_candidates#_~_text=In%201848%2C%20Frederick%20Douglass%20became'),
 ('en.wikipedia.org_wiki_List_of_Billboard_200_number-one_albums_of_1999#_~_text=Millennium%20became%20the%20best%2Dselling,nomination%20at%20the%20Grammy%20Awards..html',
  'https://en.wikipedia.org/wiki/List_of_Billboard_200_number-one_albums_of_1999#_~_text=Millennium%20became%20the%20best%2Dselling,nomination%20at%20the%20Grammy%20Awards.'),
 ('en.wikipedia.org_wiki_List_of_Billboard_200_number-one_albums_of_1999#_~_text=Millennium%20became%20the%20best%2Dselling.html',
  'https://en.wikipedia.org/wiki/List_of_Billboard_200_number-one_albums_of_1999#_~_text=Millennium%20became%20the%20best%2Dselling'),
 ('en.wikipedia.org_wiki_List_of_Copa_Am%C3%A9rica_finals#Finals.html',
  'https://en.wikipedia.org/wiki/List_of_Copa_Am%C3%A9rica_finals#Finals'),
 ('en.wikipedia.org_wiki_List_of_Hot_Ones_episodes#Season_23_(2024).html',
  'https://en.wikipedia.org/wiki/List_of_Hot_Ones_episodes#Season_23_(2024)'),
 ('en.wikipedia.org_wiki_List_of_How_I_Met_Your_Mother_episodes#Season_3_(2007%E2%80%9308).html',
  'https://en.wikipedia.org/wiki/List_of_How_I_Met_Your_Mother_episodes#Season_3_(2007%E2%80%9308)'),
 ('en.wikipedia.org_wiki_List_of_Liverpool_F.C._managers#Managers.html',
  'https://en.wikipedia.org/wiki/List_of_Liverpool_F.C._managers#Managers'),
 ('en.wikipedia.org_wiki_List_of_MLS_Cup_finals#Results_by_team.html',
  'https://en.wikipedia.org/wiki/List_of_MLS_Cup_finals#Results_by_team'),
 ('en.wikipedia.org_wiki_List_of_New_Girl_episodes#Season_2_(2012%E2%80%9313).html',
  'https://en.wikipedia.org/wiki/List_of_New_Girl_episodes#Season_2_(2012%E2%80%9313)'),
 ('en.wikipedia.org_wiki_List_of_New_Zealand_Test_cricket_records#Most_career_runs.html',
  'https://en.wikipedia.org/wiki/List_of_New_Zealand_Test_cricket_records#Most_career_runs'),
 ('en.wikipedia.org_wiki_List_of_Nobel_laureates_in_Literature#1960.html',
  'https://en.wikipedia.org/wiki/List_of_Nobel_laureates_in_Literature#1960'),
 ('en.wikipedia.org_wiki_List_of_Northern_Ireland_international_footballers#List_of_players.html',
  'https://en.wikipedia.org/wiki/List_of_Northern_Ireland_international_footballers#List_of_players'),
 ('en.wikipedia.org_wiki_List_of_S%26P_500_companies.html',
  'https://en.wikipedia.org/wiki/List_of_S%26P_500_companies'),
 ('en.wikipedia.org_wiki_List_of_Star_Wars_film_actors#Introduced_in_The_Skywalker_Saga.html',
  'https://en.wikipedia.org/wiki/List_of_Star_Wars_film_actors#Introduced_in_The_Skywalker_Saga'),
 ('en.wikipedia.org_wiki_List_of_Walt_Disney_Animation_Studios_films#ep29.html',
  'https://en.wikipedia.org/wiki/List_of_Walt_Disney_Animation_Studios_films#ep29'),
 ('en.wikipedia.org_wiki_List_of_Wildlife_Species_at_Risk_(Canada)#Amphibians.html',
  'https://en.wikipedia.org/wiki/List_of_Wildlife_Species_at_Risk_(Canada)#Amphibians'),
 ('en.wikipedia.org_wiki_List_of_World_Series_champions#World_Series_results.html',
  'https://en.wikipedia.org/wiki/List_of_World_Series_champions#World_Series_results'),
 ('en.wikipedia.org_wiki_List_of_awards_and_nominations_received_by_Katy_Perry#Awards_and_nominations.html',
  'https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Katy_Perry#Awards_and_nominations'),
 ('en.wikipedia.org_wiki_List_of_awards_and_nominations_received_by_Taylor_Swift#Honorary_degree.html',
  'https://en.wikipedia.org/wiki/List_of_awards_and_nominations_received_by_Taylor_Swift#Honorary_degree'),
 ('en.wikipedia.org_wiki_List_of_minor_planets__8001%E2%80%939000#323c.html',
  'https://en.wikipedia.org/wiki/List_of_minor_planets:_8001%E2%80%939000#323c'),
 ('en.wikipedia.org_wiki_List_of_presidents_of_France#Presidents_2.html',
  'https://en.wikipedia.org/wiki/List_of_presidents_of_France#Presidents_2'),
 ('en.wikipedia.org_wiki_List_of_presidents_of_the_United_States#Presidents.html',
  'https://en.wikipedia.org/wiki/List_of_presidents_of_the_United_States#Presidents'),
 ('en.wikipedia.org_wiki_List_of_prime_ministers_of_Australia#.html',
  'https://en.wikipedia.org/wiki/List_of_prime_ministers_of_Australia#'),
 ('en.wikipedia.org_wiki_List_of_prime_ministers_of_Canada#Prime_ministers.html',
  'https://en.wikipedia.org/wiki/List_of_prime_ministers_of_Canada#Prime_ministers'),
 ('en.wikipedia.org_wiki_List_of_vetoed_United_Nations_Security_Council_resolutions#Resolutions.html',
  'https://en.wikipedia.org/wiki/List_of_vetoed_United_Nations_Security_Council_resolutions#Resolutions'),
 ('en.wikipedia.org_wiki_List_of_waterfalls_by_height#By_overall_height.html',
  'https://en.wikipedia.org/wiki/List_of_waterfalls_by_height#By_overall_height'),
 ('en.wikipedia.org_wiki_Lists_of_airports#By_code.html', 'https://en.wikipedia.org/wiki/Lists_of_airports#By_code'),
 ('en.wikipedia.org_wiki_Lists_of_earthquakes#Largest_earthquakes_by_magnitude.html',
  'https://en.wikipedia.org/wiki/Lists_of_earthquakes#Largest_earthquakes_by_magnitude'),
 ('en.wikipedia.org_wiki_Literary_and_Philosophical_Society_of_Newcastle_upon_Tyne#.html',
  'https://en.wikipedia.org/wiki/Literary_and_Philosophical_Society_of_Newcastle_upon_Tyne#'),
 ('en.wikipedia.org_wiki_London_Broncos#1994%E2%80%932005__Broncos_and_Super_League.html',
  'https://en.wikipedia.org/wiki/London_Broncos#1994%E2%80%932005__Broncos_and_Super_League'),
 ('en.wikipedia.org_wiki_Louis_XVI#.html', 'https://en.wikipedia.org/wiki/Louis_XVI#'),
 ('en.wikipedia.org_wiki_Lynn_Rogers_(politician)#Career.html',
  'https://en.wikipedia.org/wiki/Lynn_Rogers_(politician)#Career'),
 ('en.wikipedia.org_wiki_Ma%C5%82gorzata_Ro%C5%BCniecka.html',
  'https://en.wikipedia.org/wiki/Ma%C5%82gorzata_Ro%C5%BCniecka'),
 ('en.wikipedia.org_wiki_MacArthur_Fellows_Program#.html', 'https://en.wikipedia.org/wiki/MacArthur_Fellows_Program#'),
 ('en.wikipedia.org_wiki_Mali#Ethnic_groups.html', 'https://en.wikipedia.org/wiki/Mali#Ethnic_groups'),
 ('en.wikipedia.org_wiki_Marathon_County.html', 'https://en.wikipedia.org/wiki/Marathon_County'),
 ('en.wikipedia.org_wiki_Margaret_Mansfield.html', 'https://en.wikipedia.org/wiki/Margaret_Mansfield'),
 ('en.wikipedia.org_wiki_Mark_Harvey_(arachnologist)#Achievements,_awards_and_recognition.html',
  'https://en.wikipedia.org/wiki/Mark_Harvey_(arachnologist)#Achievements,_awards_and_recognition'),
 ('en.wikipedia.org_wiki_Mark_Harvey_(arachnologist)#Achievements.html',
  'https://en.wikipedia.org/wiki/Mark_Harvey_(arachnologist)#Achievements'),
 ('en.wikipedia.org_wiki_Mark_O%27Halloran_(rugby_league).html',
  'https://en.wikipedia.org/wiki/Mark_O%27Halloran_(rugby_league)'),
 ('en.wikipedia.org_wiki_McDonald%27s.html', 'https://en.wikipedia.org/wiki/McDonald%27s'),
 ('en.wikipedia.org_wiki_Meat_Loaf#Personal_life.html', 'https://en.wikipedia.org/wiki/Meat_Loaf#Personal_life'),
 ('en.wikipedia.org_wiki_Member_states_of_the_Commonwealth_of_Nations#_~_text=The%20Republic%20of%20Ireland%20(as,former%20members%20of%20the%20Commonwealth..html',
  'https://en.wikipedia.org/wiki/Member_states_of_the_Commonwealth_of_Nations#_~_text=The%20Republic%20of%20Ireland%20(as,former%20members%20of%20the%20Commonwealth.'),
 ('en.wikipedia.org_wiki_Member_states_of_the_Commonwealth_of_Nations#_~_text=The%20Republic%20of%20Ireland%20(as.html',
  'https://en.wikipedia.org/wiki/Member_states_of_the_Commonwealth_of_Nations#_~_text=The%20Republic%20of%20Ireland%20(as'),
 ('en.wikipedia.org_wiki_Miasma_theory#.html', 'https://en.wikipedia.org/wiki/Miasma_theory#'),
 ('en.wikipedia.org_wiki_Michelson%E2%80%93Morley_experiment.html',
  'https://en.wikipedia.org/wiki/Michelson%E2%80%93Morley_experiment'),
 ('en.wikipedia.org_wiki_Milo%C5%A1_Beleslin.html', 'https://en.wikipedia.org/wiki/Milo%C5%A1_Beleslin'),
 ('en.wikipedia.org_wiki_Minamidait%C5%8Djima.html', 'https://en.wikipedia.org/wiki/Minamidait%C5%8Djima'),
 ('en.wikipedia.org_wiki_Mona_Lisa#Refuge,_theft,_and_vandalism.html',
  'https://en.wikipedia.org/wiki/Mona_Lisa#Refuge,_theft,_and_vandalism'),
 ('en.wikipedia.org_wiki_Mona_Lisa#Refuge.html', 'https://en.wikipedia.org/wiki/Mona_Lisa#Refuge'),
 ('en.wikipedia.org_wiki_Morgana_King#Film_debut.html', 'https://en.wikipedia.org/wiki/Morgana_King#Film_debut'),
 ('en.wikipedia.org_wiki_Mount_Rushmore#History.html', 'https://en.wikipedia.org/wiki/Mount_Rushmore#History'),
 ('en.wikipedia.org_wiki_Murray_State_University#Former_Presidents_of_the_University.html',
  'https://en.wikipedia.org/wiki/Murray_State_University#Former_Presidents_of_the_University'),
 ('en.wikipedia.org_wiki_NCAA_Division_III_men%27s_cross_country_championships.html',
  'https://en.wikipedia.org/wiki/NCAA_Division_III_men%27s_cross_country_championships'),
 ('en.wikipedia.org_wiki_NCT_(group)#Members.html', 'https://en.wikipedia.org/wiki/NCT_(group)#Members'),
 ('en.wikipedia.org_wiki_Nancy_Farmer#Bibliography.html', 'https://en.wikipedia.org/wiki/Nancy_Farmer#Bibliography'),
 ('en.wikipedia.org_wiki_Nashville.html', 'https://en.wikipedia.org/wiki/Nashville'),
 ('en.wikipedia.org_wiki_Navy_%E2%80%93_Merchant_Marine_Memorial.html',
  'https://en.wikipedia.org/wiki/Navy_%E2%80%93_Merchant_Marine_Memorial'),
 ('en.wikipedia.org_wiki_Nelson_Mandela#Imprisonment.html',
  'https://en.wikipedia.org/wiki/Nelson_Mandela#Imprisonment'),
 ('en.wikipedia.org_wiki_New_Girl#Episodes.html', 'https://en.wikipedia.org/wiki/New_Girl#Episodes'),
 ('en.wikipedia.org_wiki_Nick_Jonas#Personal_life.html', 'https://en.wikipedia.org/wiki/Nick_Jonas#Personal_life'),
 ('en.wikipedia.org_wiki_Nike.html', 'https://en.wikipedia.org/wiki/Nike'),
 ('en.wikipedia.org_wiki_Nim_Chimpsky#Quotations.html', 'https://en.wikipedia.org/wiki/Nim_Chimpsky#Quotations'),
 ('en.wikipedia.org_wiki_Nineteenth_Dynasty_of_Egypt#Pharaohs_of_the_19th_Dynasty.html',
  'https://en.wikipedia.org/wiki/Nineteenth_Dynasty_of_Egypt#Pharaohs_of_the_19th_Dynasty'),
 ('en.wikipedia.org_wiki_Noam_Chomsky#In_academia.html', 'https://en.wikipedia.org/wiki/Noam_Chomsky#In_academia'),
 ('en.wikipedia.org_wiki_Nobel_Prize#Multiple_laureates.html',
  'https://en.wikipedia.org/wiki/Nobel_Prize#Multiple_laureates'),
 ('en.wikipedia.org_wiki_Norman.html', 'https://en.wikipedia.org/wiki/Norman'),
 ('en.wikipedia.org_wiki_Northern_California#Cities.html', 'https://en.wikipedia.org/wiki/Northern_California#Cities'),
 ('en.wikipedia.org_wiki_Novake,_Polj%C4%8Dane.html', 'https://en.wikipedia.org/wiki/Novake,_Polj%C4%8Dane'),
 ('en.wikipedia.org_wiki_Ol%27_Dirty_Bastard.html', 'https://en.wikipedia.org/wiki/Ol%27_Dirty_Bastard'),
 ('en.wikipedia.org_wiki_Ospedale_della_Piet%C3%A0.html', 'https://en.wikipedia.org/wiki/Ospedale_della_Piet%C3%A0'),
 ('en.wikipedia.org_wiki_Paducah.html', 'https://en.wikipedia.org/wiki/Paducah'),
 ('en.wikipedia.org_wiki_Pain_%26_Gain.html', 'https://en.wikipedia.org/wiki/Pain_%26_Gain'),
 ('en.wikipedia.org_wiki_Panic_Room#Theatrical_run.html', 'https://en.wikipedia.org/wiki/Panic_Room#Theatrical_run'),
 ('en.wikipedia.org_wiki_Patrick_Kane#Early_life.html', 'https://en.wikipedia.org/wiki/Patrick_Kane#Early_life'),
 ('en.wikipedia.org_wiki_Pelee.html', 'https://en.wikipedia.org/wiki/Pelee'),
 ('en.wikipedia.org_wiki_Phil_Quartararo#Warner_Bros._Records.html',
  'https://en.wikipedia.org/wiki/Phil_Quartararo#Warner_Bros._Records'),
 ('en.wikipedia.org_wiki_Philadelphia_Waterdogs#Season_results.html',
  'https://en.wikipedia.org/wiki/Philadelphia_Waterdogs#Season_results'),
 ('en.wikipedia.org_wiki_Philip_K._Dick#Career.html', 'https://en.wikipedia.org/wiki/Philip_K._Dick#Career'),
 ('en.wikipedia.org_wiki_Philosophi%C3%A6_Naturalis_Principia_Mathematica.html',
  'https://en.wikipedia.org/wiki/Philosophi%C3%A6_Naturalis_Principia_Mathematica'),
 ('en.wikipedia.org_wiki_Pok%C3%A9mon.html', 'https://en.wikipedia.org/wiki/Pok%C3%A9mon'),
 ('en.wikipedia.org_wiki_Pok%C3%A9mon_Diamond_and_Pearl.html',
  'https://en.wikipedia.org/wiki/Pok%C3%A9mon_Diamond_and_Pearl'),
 ('en.wikipedia.org_wiki_Pok%C3%A9mon_World_Championships.html',
  'https://en.wikipedia.org/wiki/Pok%C3%A9mon_World_Championships'),
 ('en.wikipedia.org_wiki_Portage_County.html', 'https://en.wikipedia.org/wiki/Portage_County'),
 ('en.wikipedia.org_wiki_Portland.html', 'https://en.wikipedia.org/wiki/Portland'),
 ('en.wikipedia.org_wiki_Prague#_~_text=Prague%20is%20located%20approximately%20at,N%2014%C2%B025%E2%80%B2E..html',
  'https://en.wikipedia.org/wiki/Prague#_~_text=Prague%20is%20located%20approximately%20at,N%2014%C2%B025%E2%80%B2E.'),
 ('en.wikipedia.org_wiki_Prague#_~_text=Prague%20is%20located%20approximately%20at.html',
  'https://en.wikipedia.org/wiki/Prague#_~_text=Prague%20is%20located%20approximately%20at'),
 ('en.wikipedia.org_wiki_President_of_the_United_States#History_and_development.html',
  'https://en.wikipedia.org/wiki/President_of_the_United_States#History_and_development'),
 ('en.wikipedia.org_wiki_Pride_%26_Prejudice_(2005_film).html',
  'https://en.wikipedia.org/wiki/Pride_%26_Prejudice_(2005_film)'),
 ('en.wikipedia.org_wiki_Pride_and_Prejudice#Film,_television_and_theatre.html',
  'https://en.wikipedia.org/wiki/Pride_and_Prejudice#Film,_television_and_theatre'),
 ('en.wikipedia.org_wiki_Pride_and_Prejudice#Film.html', 'https://en.wikipedia.org/wiki/Pride_and_Prejudice#Film'),
 ('en.wikipedia.org_wiki_Prince_Andrew.html', 'https://en.wikipedia.org/wiki/Prince_Andrew'),
 ('en.wikipedia.org_wiki_Prince_Edward.html', 'https://en.wikipedia.org/wiki/Prince_Edward'),
 ('en.wikipedia.org_wiki_Prince_Philip.html', 'https://en.wikipedia.org/wiki/Prince_Philip'),
 ('en.wikipedia.org_wiki_Prinsjesdag#History.html', 'https://en.wikipedia.org/wiki/Prinsjesdag#History'),
 ('en.wikipedia.org_wiki_Pro_Bowl#Players_with_most_invitations.html',
  'https://en.wikipedia.org/wiki/Pro_Bowl#Players_with_most_invitations'),
 ('en.wikipedia.org_wiki_Professional_wrestling#Occupational_hazards.html',
  'https://en.wikipedia.org/wiki/Professional_wrestling#Occupational_hazards'),
 ('en.wikipedia.org_wiki_Province_of_A_Coru%C3%B1a.html', 'https://en.wikipedia.org/wiki/Province_of_A_Coru%C3%B1a'),
 ('en.wikipedia.org_wiki_Provo.html', 'https://en.wikipedia.org/wiki/Provo'),
 ('en.wikipedia.org_wiki_Pseudoscorpion#Classification.html',
  'https://en.wikipedia.org/wiki/Pseudoscorpion#Classification'),
 ('en.wikipedia.org_wiki_Pterostylis_aestiva#Description.html',
  'https://en.wikipedia.org/wiki/Pterostylis_aestiva#Description'),
 ('en.wikipedia.org_wiki_Pulitzer_Prize_for_Fiction#Repeat_winners.html',
  'https://en.wikipedia.org/wiki/Pulitzer_Prize_for_Fiction#Repeat_winners'),
 ('en.wikipedia.org_wiki_Qufu#Geography.html', 'https://en.wikipedia.org/wiki/Qufu#Geography'),
 ('en.wikipedia.org_wiki_Red_Hot_Chili_Peppers#Discography.html',
  'https://en.wikipedia.org/wiki/Red_Hot_Chili_Peppers#Discography'),
 ('en.wikipedia.org_wiki_Remy%27s_Ratatouille_Adventure.html',
  'https://en.wikipedia.org/wiki/Remy%27s_Ratatouille_Adventure'),
 ('en.wikipedia.org_wiki_Ren%C4%8De.html', 'https://en.wikipedia.org/wiki/Ren%C4%8De'),
 ('en.wikipedia.org_wiki_Resident_Evil__Revelations_2#.html',
  'https://en.wikipedia.org/wiki/Resident_Evil__Revelations_2#'),
 ('en.wikipedia.org_wiki_Revive_%26_Restore.html', 'https://en.wikipedia.org/wiki/Revive_%26_Restore'),
 ('en.wikipedia.org_wiki_River_Avon,_Bristol#Hydrology_and_water_quality.html',
  'https://en.wikipedia.org/wiki/River_Avon,_Bristol#Hydrology_and_water_quality'),
 ('en.wikipedia.org_wiki_River_Avon.html', 'https://en.wikipedia.org/wiki/River_Avon'),
 ('en.wikipedia.org_wiki_Roberto_%C3%81lamo.html', 'https://en.wikipedia.org/wiki/Roberto_%C3%81lamo'),
 ('en.wikipedia.org_wiki_Rodrigo_Pacheco_M%C3%A9ndez.html',
  'https://en.wikipedia.org/wiki/Rodrigo_Pacheco_M%C3%A9ndez'),
 ('en.wikipedia.org_wiki_Rubik%27s_Cube.html', 'https://en.wikipedia.org/wiki/Rubik%27s_Cube'),
 ('en.wikipedia.org_wiki_Russian_Bishop%27s_House.html', 'https://en.wikipedia.org/wiki/Russian_Bishop%27s_House'),
 ('en.wikipedia.org_wiki_Sailing_at_the_1984_Summer_Olympics_%E2%80%93_470.html',
  'https://en.wikipedia.org/wiki/Sailing_at_the_1984_Summer_Olympics_%E2%80%93_470'),
 ('en.wikipedia.org_wiki_San_Jose.html', 'https://en.wikipedia.org/wiki/San_Jose'),
 ('en.wikipedia.org_wiki_Saturday_Night_Live#Controversies.html',
  'https://en.wikipedia.org/wiki/Saturday_Night_Live#Controversies'),
 ('en.wikipedia.org_wiki_Saving_Private_Ryan#Reception.html',
  'https://en.wikipedia.org/wiki/Saving_Private_Ryan#Reception'),
 ('en.wikipedia.org_wiki_Schindler%27s_List.html', 'https://en.wikipedia.org/wiki/Schindler%27s_List'),
 ('en.wikipedia.org_wiki_Se%C3%A1n_Mac_Diarmada.html', 'https://en.wikipedia.org/wiki/Se%C3%A1n_Mac_Diarmada'),
 ('en.wikipedia.org_wiki_Sea_Cliff.html', 'https://en.wikipedia.org/wiki/Sea_Cliff'),
 ('en.wikipedia.org_wiki_Sens%C5%8D-ji.html', 'https://en.wikipedia.org/wiki/Sens%C5%8D-ji'),
 ('en.wikipedia.org_wiki_Seven_Wonders_of_the_Ancient_World#Wonders.html',
  'https://en.wikipedia.org/wiki/Seven_Wonders_of_the_Ancient_World#Wonders'),
 ('en.wikipedia.org_wiki_She%27s_All_That.html', 'https://en.wikipedia.org/wiki/She%27s_All_That'),
 ('en.wikipedia.org_wiki_Shrek#Accolades.html', 'https://en.wikipedia.org/wiki/Shrek#Accolades'),
 ('en.wikipedia.org_wiki_Shreve,_Lamb_%26_Harmon.html', 'https://en.wikipedia.org/wiki/Shreve,_Lamb_%26_Harmon'),
 ('en.wikipedia.org_wiki_Shreve.html', 'https://en.wikipedia.org/wiki/Shreve'),
 ('en.wikipedia.org_wiki_Solomon_Sea#Deepest_point.html', 'https://en.wikipedia.org/wiki/Solomon_Sea#Deepest_point'),
 ('en.wikipedia.org_wiki_Speech_from_the_throne#Netherlands.html',
  'https://en.wikipedia.org/wiki/Speech_from_the_throne#Netherlands'),
 ('en.wikipedia.org_wiki_Spokane_University#Notable_alumni.html',
  'https://en.wikipedia.org/wiki/Spokane_University#Notable_alumni'),
 ('en.wikipedia.org_wiki_SpongeBob_SquarePants#Franchise.html',
  'https://en.wikipedia.org/wiki/SpongeBob_SquarePants#Franchise'),
 ('en.wikipedia.org_wiki_Spyro_2__Ripto%27s_Rage!.html', 'https://en.wikipedia.org/wiki/Spyro_2:_Ripto%27s_Rage!'),
 ('en.wikipedia.org_wiki_St._Philip%27s_College_(United_States).html',
  'https://en.wikipedia.org/wiki/St._Philip%27s_College_(United_States)'),
 ('en.wikipedia.org_wiki_Stephen_Hawking#1975%E2%80%931990.html',
  'https://en.wikipedia.org/wiki/Stephen_Hawking#1975%E2%80%931990'),
 ('en.wikipedia.org_wiki_Steve_Carell#2004%E2%80%932013__The_Office_and_comedic_roles.html',
  'https://en.wikipedia.org/wiki/Steve_Carell#2004%E2%80%932013__The_Office_and_comedic_roles'),
 ('en.wikipedia.org_wiki_Strong_Love_Affair#Track_listing.html',
  'https://en.wikipedia.org/wiki/Strong_Love_Affair#Track_listing'),
 ('en.wikipedia.org_wiki_Super_Bowl_XXIX#_~_text=The%2049ers%20defeated%20the%20Chargers,ravaged%20the%20city%20in%201992..html',
  'https://en.wikipedia.org/wiki/Super_Bowl_XXIX#_~_text=The%2049ers%20defeated%20the%20Chargers,ravaged%20the%20city%20in%201992.'),
 ('en.wikipedia.org_wiki_Super_Bowl_XXIX#_~_text=The%2049ers%20defeated%20the%20Chargers.html',
  'https://en.wikipedia.org/wiki/Super_Bowl_XXIX#_~_text=The%2049ers%20defeated%20the%20Chargers'),
 ('en.wikipedia.org_wiki_Superman_%26_Bugs_Bunny.html', 'https://en.wikipedia.org/wiki/Superman_%26_Bugs_Bunny'),
 ('en.wikipedia.org_wiki_Swimming_at_the_1948_Summer_Olympics_%E2%80%93_Men%27s_100_metre_freestyle.html',
  'https://en.wikipedia.org/wiki/Swimming_at_the_1948_Summer_Olympics_%E2%80%93_Men%27s_100_metre_freestyle'),
 ('en.wikipedia.org_wiki_Synsphyronus#Species.html', 'https://en.wikipedia.org/wiki/Synsphyronus#Species'),
 ('en.wikipedia.org_wiki_Takarazuka,_Hy%C5%8Dgo.html', 'https://en.wikipedia.org/wiki/Takarazuka,_Hy%C5%8Dgo'),
 ('en.wikipedia.org_wiki_Takarazuka.html', 'https://en.wikipedia.org/wiki/Takarazuka'),
 ('en.wikipedia.org_wiki_Target_House.html', 'https://en.wikipedia.org/wiki/Target_House'),
 ('en.wikipedia.org_wiki_Taylor_Swift#.html', 'https://en.wikipedia.org/wiki/Taylor_Swift#'),
 ('en.wikipedia.org_wiki_Tennessee_Coal.html', 'https://en.wikipedia.org/wiki/Tennessee_Coal'),
 ('en.wikipedia.org_wiki_Tennis_at_the_1988_Summer_Olympics_%E2%80%93_Women%27s_singles.html',
  'https://en.wikipedia.org/wiki/Tennis_at_the_1988_Summer_Olympics_%E2%80%93_Women%27s_singles'),
 ('en.wikipedia.org_wiki_Terrorism_in_the_United_States#Deadliest_attacks.html',
  'https://en.wikipedia.org/wiki/Terrorism_in_the_United_States#Deadliest_attacks'),
 ('en.wikipedia.org_wiki_Thailand_national_football_team#Coaching_history.html',
  'https://en.wikipedia.org/wiki/Thailand_national_football_team#Coaching_history'),
 ('en.wikipedia.org_wiki_That%27s_What_Friends_Are_For.html',
  'https://en.wikipedia.org/wiki/That%27s_What_Friends_Are_For'),
 ('en.wikipedia.org_wiki_The_Apollo.html', 'https://en.wikipedia.org/wiki/The_Apollo'),
 ('en.wikipedia.org_wiki_The_Band#Discography.html', 'https://en.wikipedia.org/wiki/The_Band#Discography'),
 ('en.wikipedia.org_wiki_The_Beach_Boys#History.html', 'https://en.wikipedia.org/wiki/The_Beach_Boys#History'),
 ('en.wikipedia.org_wiki_The_Duke_of_Edinburgh%27s_Award.html',
  'https://en.wikipedia.org/wiki/The_Duke_of_Edinburgh%27s_Award'),
 ('en.wikipedia.org_wiki_The_Old_Man_and_the_Sea#Reception_and_legacy.html',
  'https://en.wikipedia.org/wiki/The_Old_Man_and_the_Sea#Reception_and_legacy'),
 ('en.wikipedia.org_wiki_The_Seduction_of_Joe_Tynan#Awards.html',
  'https://en.wikipedia.org/wiki/The_Seduction_of_Joe_Tynan#Awards'),
 ('en.wikipedia.org_wiki_Thirteen_Years%27_War_(1454%E2%80%931466).html',
  'https://en.wikipedia.org/wiki/Thirteen_Years%27_War_(1454%E2%80%931466)'),
 ('en.wikipedia.org_wiki_Tiny_Tina%27s_Wonderlands.html', 'https://en.wikipedia.org/wiki/Tiny_Tina%27s_Wonderlands'),
 ('en.wikipedia.org_wiki_Tom%C3%A1%C5%A1_Pekhart.html', 'https://en.wikipedia.org/wiki/Tom%C3%A1%C5%A1_Pekhart'),
 ('en.wikipedia.org_wiki_Tony_Hawk%27s_Pro_Skater.html', 'https://en.wikipedia.org/wiki/Tony_Hawk%27s_Pro_Skater'),
 ('en.wikipedia.org_wiki_Toronto_Maple_Leafs#Season-by-season_record.html',
  'https://en.wikipedia.org/wiki/Toronto_Maple_Leafs#Season-by-season_record'),
 ('en.wikipedia.org_wiki_Trans%E2%80%93West_African_Coastal_Highway.html',
  'https://en.wikipedia.org/wiki/Trans%E2%80%93West_African_Coastal_Highway'),
 ('en.wikipedia.org_wiki_Triple_Crown_of_Thoroughbred_Racing_(United_States)#Winners_of_the_Triple_Crown.html',
  'https://en.wikipedia.org/wiki/Triple_Crown_of_Thoroughbred_Racing_(United_States)#Winners_of_the_Triple_Crown'),
 ('en.wikipedia.org_wiki_Tulsa.html', 'https://en.wikipedia.org/wiki/Tulsa'),
 ('en.wikipedia.org_wiki_United_States_federal_executive_departments#Former_departments.html',
  'https://en.wikipedia.org/wiki/United_States_federal_executive_departments#Former_departments'),
 ('en.wikipedia.org_wiki_University_of_Illinois_Urbana-Champaign#Notable_alumni_and_faculty.html',
  'https://en.wikipedia.org/wiki/University_of_Illinois_Urbana-Champaign#Notable_alumni_and_faculty'),
 ('en.wikipedia.org_wiki_University_of_Maryland,_College_Park#Notable_alumni.html',
  'https://en.wikipedia.org/wiki/University_of_Maryland,_College_Park#Notable_alumni'),
 ('en.wikipedia.org_wiki_University_of_Maryland.html', 'https://en.wikipedia.org/wiki/University_of_Maryland'),
 ('en.wikipedia.org_wiki_University_of_Oxford#Mathematics_and_sciences.html',
  'https://en.wikipedia.org/wiki/University_of_Oxford#Mathematics_and_sciences'),
 ('en.wikipedia.org_wiki_Upper_Franconia#Coat_of_arms.html',
  'https://en.wikipedia.org/wiki/Upper_Franconia#Coat_of_arms'),
 ('en.wikipedia.org_wiki_Utah_County.html', 'https://en.wikipedia.org/wiki/Utah_County'),
 ('en.wikipedia.org_wiki_Warner_Records#End_of_an_era__Ostin_and_Waronker_depart.html',
  'https://en.wikipedia.org/wiki/Warner_Records#End_of_an_era__Ostin_and_Waronker_depart'),
 ('en.wikipedia.org_wiki_Waterville.html', 'https://en.wikipedia.org/wiki/Waterville'),
 ('en.wikipedia.org_wiki_Weekly_Sh%C5%8Dnen_Jump.html', 'https://en.wikipedia.org/wiki/Weekly_Sh%C5%8Dnen_Jump'),
 ('en.wikipedia.org_wiki_Wendy%27s.html', 'https://en.wikipedia.org/wiki/Wendy%27s'),
 ('en.wikipedia.org_wiki_Westfield.html', 'https://en.wikipedia.org/wiki/Westfield'),
 ('en.wikipedia.org_wiki_Wheatland.html', 'https://en.wikipedia.org/wiki/Wheatland'),
 ('en.wikipedia.org_wiki_Whiplash_(2014_film)#.html', 'https://en.wikipedia.org/wiki/Whiplash_(2014_film)#'),
 ('en.wikipedia.org_wiki_William.html', 'https://en.wikipedia.org/wiki/William'),
 ('en.wikipedia.org_wiki_William_Mansfield.html', 'https://en.wikipedia.org/wiki/William_Mansfield'),
 ('en.wikipedia.org_wiki_Willie_Mays#.html', 'https://en.wikipedia.org/wiki/Willie_Mays#'),
 ('en.wikipedia.org_wiki_Women%27s_Tennis_Association.html',
  'https://en.wikipedia.org/wiki/Women%27s_Tennis_Association'),
 ('en.wikipedia.org_wiki_Women_in_Film_Crystal_%2B_Lucy_Awards#Dorothy_Arzner_Directors_award.html',
  'https://en.wikipedia.org/wiki/Women_in_Film_Crystal_%2B_Lucy_Awards#Dorothy_Arzner_Directors_award'),
 ('en.wikipedia.org_wiki_Wood_County.html', 'https://en.wikipedia.org/wiki/Wood_County'),
 ('en.wikipedia.org_wiki_World%27s_Columbian_Exposition.html',
  'https://en.wikipedia.org/wiki/World%27s_Columbian_Exposition'),
 ('en.wikipedia.org_wiki_World_War_I#.html', 'https://en.wikipedia.org/wiki/World_War_I#'),
 ('en.wikipedia.org_wiki_WrestleMania_13#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_13#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_21#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_21#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_22#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_22#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_23#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_23#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_25#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_25#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_29#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_29#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_IX#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_IX#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_VII#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_VII#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_VIII#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_VIII#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_X-Seven#Results.html',
  'https://en.wikipedia.org/wiki/WrestleMania_X-Seven#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_X8#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_X8#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XI#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XI#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XII#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XII#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XIV#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XIV#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XIX#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XIX#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XV#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XV#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XX#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XX#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XXIV#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XXIV#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XXVI#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XXVI#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XXVII#Results.html', 'https://en.wikipedia.org/wiki/WrestleMania_XXVII#Results'),
 ('en.wikipedia.org_wiki_WrestleMania_XXVIII#Results.html',
  'https://en.wikipedia.org/wiki/WrestleMania_XXVIII#Results'),
 ('en.wikipedia.org_wiki_Wrestling_at_the_1960_Summer_Olympics_%E2%80%93_Men%27s_Greco-Roman_bantamweight.html',
  'https://en.wikipedia.org/wiki/Wrestling_at_the_1960_Summer_Olympics_%E2%80%93_Men%27s_Greco-Roman_bantamweight'),
 ('en.wikipedia.org_wiki_Wrestling_at_the_2020_Summer_Olympics#Medalists.html',
  'https://en.wikipedia.org/wiki/Wrestling_at_the_2020_Summer_Olympics#Medalists'),
 ('en.wikipedia.org_wiki_Wrestling_at_the_2020_Summer_Olympics_%E2%80%93_Men%27s_freestyle_86_kg.html',
  'https://en.wikipedia.org/wiki/Wrestling_at_the_2020_Summer_Olympics_%E2%80%93_Men%27s_freestyle_86_kg'),
 ('en.wikipedia.org_wiki_Wroc%C5%82aw.html', 'https://en.wikipedia.org/wiki/Wroc%C5%82aw'),
 ('en.wikipedia.org_wiki_Wroc%C5%82aw_Dwarfs.html', 'https://en.wikipedia.org/wiki/Wroc%C5%82aw_Dwarfs'),
 ('en.wikipedia.org_wiki_Wyandotte.html', 'https://en.wikipedia.org/wiki/Wyandotte'),
 ('en.wikipedia.org_wiki_You_(TV_series)#Season_2_(2019).html',
  'https://en.wikipedia.org/wiki/You_(TV_series)#Season_2_(2019)'),
 ('en.wikipedia.org_wiki_Ypsilanti.html', 'https://en.wikipedia.org/wiki/Ypsilanti'),
 ('en.wikipedia.org_wiki_Zac_Efron#Awards_and_nominations.html',
  'https://en.wikipedia.org/wiki/Zac_Efron#Awards_and_nominations'),
 ('en.wikipedia.org_wiki_Zack_Wheat#.html', 'https://en.wikipedia.org/wiki/Zack_Wheat#')]


def download_one(filename: str, url: str, out_dir: Path) -> dict:
    out_path = out_dir / filename
    result = {"filename": filename, "url": url, "ok": False, "status": None, "bytes": 0, "error": None}
    headers = {"User-Agent": USER_AGENT}

    for attempt in range(1, 4):
        try:
            request = urllib.request.Request(url, headers=headers)
            with urllib.request.urlopen(request, timeout=30) as response:
                data = response.read()
                result["status"] = getattr(response, "status", None)
                result["bytes"] = len(data)
                if result["status"] and 200 <= result["status"] < 300 and data:
                    out_path.write_bytes(data)
                    result["ok"] = True
                    return result
                result["error"] = f"unexpected status/content: status={result['status']} bytes={len(data)}"
        except urllib.error.HTTPError as exc:
            result["status"] = exc.code
            result["error"] = f"HTTPError: {exc.code} {exc.reason}"
            if exc.code == 429:
                time.sleep(15 * attempt)
                continue
            if exc.code in (404, 410):
                break
        except Exception as exc:
            result["error"] = f"{type(exc).__name__}: {exc}"

        time.sleep(0.75 * attempt)

    return result


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Download the embedded 470 additional Wikipedia HTML files."
    )
    parser.add_argument("output_folder", type=Path, help="Folder where HTML files and manifests will be written.")
    args = parser.parse_args()

    out_dir = args.output_folder
    out_dir.mkdir(parents=True, exist_ok=True)
    manifest_path = out_dir / "manifest.jsonl"

    results = []
    with ThreadPoolExecutor(max_workers=WORKERS) as pool:
        futures = [pool.submit(download_one, filename, url, out_dir) for filename, url in DOWNLOADS]
        with manifest_path.open("w", encoding="utf-8") as manifest:
            for future in as_completed(futures):
                result = future.result()
                results.append(result)
                manifest.write(json.dumps(result, ensure_ascii=False) + "\n")
                manifest.flush()

    failures = [result for result in results if not result["ok"]]
    if failures:
        failures_path = out_dir / "failures.txt"
        with failures_path.open("w", encoding="utf-8") as failure_file:
            for result in sorted(failures, key=lambda item: item["filename"]):
                failure_file.write(
                    f"{result['filename']}\t{result['url']}\t{result['status']}\t{result['error']}\n"
                )
    else:
        failures_path = None

    summary = {
        "output_folder": str(out_dir),
        "requested": len(DOWNLOADS),
        "downloaded": sum(1 for result in results if result["ok"]),
        "failed": len(failures),
        "manifest": str(manifest_path),
        "failures": str(failures_path) if failures_path else None,
    }
    (out_dir / "summary.json").write_text(json.dumps(summary, indent=2), encoding="utf-8")
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()
