graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_llama3_1-8b,_vllm,_cuda,_valid,_r5.1-dev_default,_float16,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_llama3_1-8b,_vllm,_cuda,_valid,_r5.1-dev_default,_float16,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_llama3_1-8b,_vllm,_cuda,_valid,_r5.1-dev_default,_float16,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_llama3_1-8b,_vllm,_cuda,_valid,_r5.1-dev_default,_float16,_offline_) --> get,mlcommons,inference,src,_branch.whisper-fix,_branch.master,_repo.https://github.com/anandhu-eng/inference
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src,_branch.whisper-fix,_repo.https://github.com/anandhu-eng/inference
    app-mlperf-inference,d775cac873ee4231_(_reference,_llama3_1-8b,_vllm,_cuda,_valid,_r5.1-dev_default,_float16,_offline_) --> get,mlperf,inference,utils
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_reference,_llama3_1-8b,_vllm,_cuda,_valid,_r5.1-dev_default,_float16,_offline_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,python
    get-generic-python-lib,94b62a682bc44791_(_package.vllm_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.vllm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,ml-model,llama3,_hf,_meta-llama/Llama-3.1-8B-Instruct
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,python
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,sut,configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,mlcommons,inference,src,_branch.whisper-fix,_repo.https://github.com/anandhu-eng/inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> generate,user-conf,mlperf,inference,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,loadgen,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,mlcommons,inference,src,_branch.whisper-fix,_repo.https://github.com/anandhu-eng/inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_package.transformers_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.transformers
    get-generic-python-lib,94b62a682bc44791_(_package.sentencepiece_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.sentencepiece
    get-generic-python-lib,94b62a682bc44791_(_package.accelerate_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.accelerate
    get-generic-python-lib,94b62a682bc44791_(_package.pybind11_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.pybind11
    get-generic-python-lib,94b62a682bc44791_(_package.nltk_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.nltk
    get-generic-python-lib,94b62a682bc44791_(_package.evaluate_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.evaluate
    get-generic-python-lib,94b62a682bc44791_(_package.absl-py_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.absl-py
    get-generic-python-lib,94b62a682bc44791_(_package.rouge-score_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,generic-python-lib,_package.rouge-score
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,ml-model,llama3,_hf,_meta-llama/Llama-3.1-8B-Instruct
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> get,dataset,cnndm,_validation,_datacenter,_llama3,_mlc,_rclone
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_cuda,_vllm,_offline,_llama3_1-8b,_float16_) --> benchmark-mlperf