graph TD
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_offline_) --> detect,os
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_offline_) --> get,sys-utils-cm
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_offline_) --> get,python
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_offline_) --> get,mlcommons,inference,src
    get-mlperf-inference-utils,e341e5f86d8342e5 --> get,mlperf,inference,src
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_offline_) --> get,mlperf,inference,utils
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_offline_) --> get,dataset-aux,imagenet-aux
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,cuda,_toolkit
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,python3
    get-generic-python-lib,94b62a682bc44791_(_package.pycuda_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.pycuda
    get-generic-python-lib,94b62a682bc44791_(_package.numpy_) --> get,python3
    get-cuda-devices,7a3ede4d3558427a_(_with-pycuda_) --> get,generic-python-lib,_package.numpy
    app-mlperf-inference,d775cac873ee4231_(_reference,_resnet50,_onnxruntime,_cuda,_valid,_r5.1-dev_default,_offline_) --> get,cuda-devices,_with-pycuda
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> detect,cpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,sys-utils-cm
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,cuda,_cudnn
    get-generic-python-lib,94b62a682bc44791_(_onnxruntime_gpu_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-python-lib,_onnxruntime_gpu
    get-generic-python-lib,94b62a682bc44791_(_onnxruntime_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-python-lib,_onnxruntime
    get-generic-python-lib,94b62a682bc44791_(_onnxruntime_gpu_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-python-lib,_onnxruntime_gpu
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,ml-model,image-classification,resnet50,raw,_fp32,_onnx
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,dataset,image-classification,imagenet,preprocessed,_-for.mobilenet,_NCHW,_full
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,dataset-aux,image-classification,imagenet-aux
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,os
    detect-cpu,586c8a43320142f7 --> detect,os
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> detect,cpu
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,python
    get-mlperf-inference-sut-configs,c2fbf72009e2445b --> get,cache,dir,_name.mlperf-inference-sut-configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,sut,configs
    generate-mlperf-inference-user-conf,3af4475745964b93_(_wg-inference_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> generate,user-conf,mlperf,inference,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,loadgen,_wg-inference
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,mlcommons,inference,src
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,mlcommons,inference,src
    get-generic-python-lib,94b62a682bc44791_(_package.psutil_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-python-lib,_package.psutil
    get-generic-python-lib,94b62a682bc44791_(_opencv-python_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-python-lib,_opencv-python
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-sys-util,_libgl
    get-generic-python-lib,94b62a682bc44791_(_numpy_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-python-lib,_numpy
    get-generic-python-lib,94b62a682bc44791_(_pycocotools_) --> get,python3
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> get,generic-python-lib,_pycocotools
    detect-cpu,586c8a43320142f7 --> detect,os
    benchmark-program,19f369ef47084895 --> detect,cpu
    benchmark-program-mlperf,cfff0132a8aa4018 --> benchmark-program,program
    app-mlperf-inference-mlcommons-python,ff149e9781fc4b65_(_onnxruntime,_offline,_cuda,_resnet50,_fp32_) --> benchmark-mlperf